/**
* Note: This file was auto-generated by TI PinMux on 12/4/2020 at 3:50:50 PM.
*
* \file  AM64x_pinmux_data.c
*
* \brief  This file contains the pin mux configurations for the boards.
*         These are prepared based on how the peripherals are extended on
*         the boards.
*
* \copyright Copyright (CU) 2020 Texas Instruments Incorporated -
*             http://www.ti.com/
*/

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "AM64x_pinmux.h"

/** Peripheral Pin Configurations */


static pinmuxPerCfg_t gGpmc0PinCfg[] =
{
    /* MyGPMC1 -> GPMC0_A0 -> U2 */
    {
        PIN_PRG0_PRU0_GPO2, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A1 -> AA2 */
    {
        PIN_PRG0_PRU0_GPO4, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A10 -> U5 */
    {
        PIN_PRG0_PRU1_GPO15, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A11 -> AA4 */
    {
        PIN_PRG0_PRU1_GPO16, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A12 -> P2 */
    {
        PIN_PRG0_MDIO0_MDIO, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A13 -> P3 */
    {
        PIN_PRG0_MDIO0_MDC, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A14 -> AA3 */
    {
        PIN_PRG0_PRU0_GPO12, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A15 -> R6 */
    {
        PIN_PRG0_PRU0_GPO13, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A16 -> T5 */
    {
        PIN_PRG0_PRU0_GPO15, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A17 -> U1 */
    {
        PIN_PRG0_PRU0_GPO17, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A18 -> T4 */
    {
        PIN_PRG0_PRU1_GPO3, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A19 -> R5 */
    {
        PIN_PRG0_PRU1_GPO6, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A2 -> T2 */
    {
        PIN_PRG0_PRU0_GPO8, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A20 -> R21 */
    {
        PIN_GPMC0_CSN3, PIN_MODE(4) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A21 -> Y18 */
    {
        PIN_GPMC0_WAIT1, PIN_MODE(4) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A22 -> N16 */
    {
        PIN_GPMC0_WPN, PIN_MODE(4) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A3 -> V4 */
    {
        PIN_PRG0_PRU0_GPO14, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A4 -> U4 */
    {
        PIN_PRG0_PRU0_GPO16, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A5 -> V1 */
    {
        PIN_PRG0_PRU0_GPO18, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A6 -> W1 */
    {
        PIN_PRG0_PRU0_GPO19, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A7 -> Y4 */
    {
        PIN_PRG0_PRU1_GPO12, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A8 -> T6 */
    {
        PIN_PRG0_PRU1_GPO13, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_A9 -> U6 */
    {
        PIN_PRG0_PRU1_GPO14, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_AD0 -> T20 */
    {
        PIN_GPMC0_AD0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD1 -> U21 */
    {
        PIN_GPMC0_AD1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD10 -> R16 */
    {
        PIN_GPMC0_AD10, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD11 -> W20 */
    {
        PIN_GPMC0_AD11, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD12 -> W21 */
    {
        PIN_GPMC0_AD12, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD13 -> V18 */
    {
        PIN_GPMC0_AD13, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD14 -> Y21 */
    {
        PIN_GPMC0_AD14, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD15 -> Y20 */
    {
        PIN_GPMC0_AD15, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD16 -> Y7 */
    {
        PIN_PRG1_PRU0_GPO0, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD17 -> U8 */
    {
        PIN_PRG1_PRU0_GPO1, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD18 -> W8 */
    {
        PIN_PRG1_PRU0_GPO2, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD19 -> V8 */
    {
        PIN_PRG1_PRU0_GPO3, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD2 -> T18 */
    {
        PIN_GPMC0_AD2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD20 -> Y8 */
    {
        PIN_PRG1_PRU0_GPO4, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD21 -> V13 */
    {
        PIN_PRG1_PRU0_GPO5, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD22 -> AA7 */
    {
        PIN_PRG1_PRU0_GPO6, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD23 -> U13 */
    {
        PIN_PRG1_PRU0_GPO7, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD24 -> W13 */
    {
        PIN_PRG1_PRU0_GPO8, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD25 -> U15 */
    {
        PIN_PRG1_PRU0_GPO9, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD26 -> U14 */
    {
        PIN_PRG1_PRU0_GPO10, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD27 -> AA8 */
    {
        PIN_PRG1_PRU0_GPO11, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD28 -> U9 */
    {
        PIN_PRG1_PRU0_GPO12, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD29 -> W9 */
    {
        PIN_PRG1_PRU0_GPO13, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD3 -> U20 */
    {
        PIN_GPMC0_AD3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD30 -> AA9 */
    {
        PIN_PRG1_PRU0_GPO14, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD31 -> Y9 */
    {
        PIN_PRG1_PRU0_GPO15, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD4 -> U18 */
    {
        PIN_GPMC0_AD4, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD5 -> U19 */
    {
        PIN_GPMC0_AD5, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD6 -> V20 */
    {
        PIN_GPMC0_AD6, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD7 -> V21 */
    {
        PIN_GPMC0_AD7, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD8 -> V19 */
    {
        PIN_GPMC0_AD8, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_AD9 -> T17 */
    {
        PIN_GPMC0_AD9, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_WAIT0 -> W19 */
    {
        PIN_GPMC0_WAIT0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPMC1 -> GPMC0_BE1n -> T19 */
    {
        PIN_GPMC0_BE1N, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_CSn0 -> R19 */
    {
        PIN_GPMC0_CSN0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_CSn1 -> R20 */
    {
        PIN_GPMC0_CSN1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_CSn2 -> P19 */
    {
        PIN_GPMC0_CSN2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_ADVn_ALE -> P16 */
    {
        PIN_GPMC0_ADVN_ALE, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_OEn_REn -> R18 */
    {
        PIN_GPMC0_OEN_REN, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_WEn -> T21 */
    {
        PIN_GPMC0_WEN, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MyGPMC1 -> GPMC0_BE0n_CLE -> P17 */
    {
        PIN_GPMC0_BE0N_CLE, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gGpmcPinCfg[] =
{
    {0, TRUE, gGpmc0PinCfg},
    {PINMUX_END}
};


pinmuxBoardCfg_t gAM64x_MainPinmuxDataGPMC[] =
{
    {0, gGpmcPinCfg},
    {PINMUX_END}
};

