/*============================*/
/*      DDR MEMORY MAP        */
/*============================*/

#include "memory_map_defines.inc"

MEMORY
{
    DDR0_RESERVED       (RWIX)  : ORIGIN = DDR0_RESERVED_START      LENGTH = DDR0_RESERVED_SIZE 
    /*---------------------------------- MCU R5FSS0 CORE0 ------------------------------*/
    MCU1_0_IPC_DATA     (RWIX)	: ORIGIN = MCU1_0_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU1_0_EXT_DATA     (RWIX)	: ORIGIN = MCU1_0_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU1_0_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU1_0_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU1_0_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU1_0_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU1_0_DDR_SPACE    (RWIX)	: ORIGIN = MCU1_0_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MCU R5FSS0 CORE1 ------------------------------*/
    MCU1_1_IPC_DATA     (RWIX)	: ORIGIN = MCU1_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU1_1_EXT_DATA     (RWIX)	: ORIGIN = MCU1_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU1_1_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU1_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU1_1_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU1_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU1_1_DDR_SPACE    (RWIX)	: ORIGIN = MCU1_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 ------------------------------*/
    MCU2_0_IPC_DATA     (RWIX)	: ORIGIN = MCU2_0_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU2_0_EXT_DATA     (RWIX)	: ORIGIN = MCU2_0_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU2_0_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU2_0_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU2_0_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU2_0_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU2_0_DDR_SPACE    (RWIX)	: ORIGIN = MCU2_0_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 -----------------------------*/
    MCU2_1_IPC_DATA     (RWIX)	: ORIGIN = MCU2_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU2_1_EXT_DATA     (RWIX)	: ORIGIN = MCU2_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU2_1_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU2_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU2_1_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU2_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU2_1_DDR_SPACE    (RWIX)	: ORIGIN = MCU2_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 ------------------------------*/
    MCU3_0_IPC_DATA     (RWIX)	: ORIGIN = MCU3_0_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU3_0_EXT_DATA     (RWIX)	: ORIGIN = MCU3_0_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU3_0_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU3_0_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU3_0_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU3_0_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU3_0_DDR_SPACE    (RWIX)	: ORIGIN = MCU3_0_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 -----------------------------*/
    MCU3_1_IPC_DATA     (RWIX)	: ORIGIN = MCU3_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU3_1_EXT_DATA     (RWIX)	: ORIGIN = MCU3_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU3_1_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU3_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU3_1_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU3_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU3_1_DDR_SPACE    (RWIX)	: ORIGIN = MCU3_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- C66x DSP CORE1 ---------------------------------*/
    C66X1_IPC_D         (RWIX)	: ORIGIN = C66x1_IPC_DATA_BASE      LENGTH = IPC_DATA_SIZE
    C66X1_EXT_D         (RWIX)	: ORIGIN = C66x1_EXT_DATA_BASE      LENGTH = EXT_DATA_SIZE
    C66X1_TEXT          (RWIX)	: ORIGIN = C66x1_MEM_TEXT_BASE      LENGTH = MEM_TEXT_SIZE
    C66X1_DATA          (RWIX)	: ORIGIN = C66x1_MEM_DATA_BASE      LENGTH = MEM_DATA_SIZE
    C66X1_DDR_SPACE     (RWIX)	: ORIGIN = C66x1_DDR_SPACE_BASE     LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- C66x DSP CORE2 ---------------------------------*/
    C66X2_IPC_D         (RWIX)	: ORIGIN = C66x2_IPC_DATA_BASE      LENGTH = IPC_DATA_SIZE
    C66X2_EXT_D         (RWIX)	: ORIGIN = C66x2_EXT_DATA_BASE      LENGTH = EXT_DATA_SIZE
    C66X2_TEXT          (RWIX)	: ORIGIN = C66x2_MEM_TEXT_BASE      LENGTH = MEM_TEXT_SIZE
    C66X2_DATA          (RWIX)	: ORIGIN = C66x2_MEM_DATA_BASE      LENGTH = MEM_DATA_SIZE
    C66X2_DDR_SPACE     (RWIX)	: ORIGIN = C66x2_DDR_SPACE_BASE     LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- C7x-------- -----------------------------------*/
    C7X_IPC_D           (RWIX)	: ORIGIN = C7x_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    C7X_EXT_D           (RWIX)	: ORIGIN = C7x_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    C7X_TEXT            (RWIX)	: ORIGIN = C7x_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    C7X_DATA            (RWIX)	: ORIGIN = C7x_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    C7X_DDR_SPACE       (RWIX)	: ORIGIN = C7x_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- Shared Region ----------------------------------------*/
    SHARED_DDR_SPACE    (RWIX)	: ORIGIN = SHARED_DDR_SPACE_START  LENGTH = SHARED_DDR_SPACE_SIZE  
} 
