/**
 * Note: This file was auto-generated by TI PinMux on 4/23/2020 at 10:03:39 AM.
 *
 * \file   TPR12_evm_pinmux.h
 *
 * \brief  This file contains pad configure register offsets and bit-field 
 *         value macros for different configurations,
 *
 *           BIT[9]		    PUPDSEL		    Pullup/PullDown Selection 0 -- Pull Down
 *           BIT[8]		    PI              Pull Inhibit/Pull Disable 0 -- Enable
 *           BIT[3:0]		FUNC_SEL		Function Select
 *
 *  \copyright Copyright (CU) 2020 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

#ifndef _TPR12_PIN_MUX_H_
#define _TPR12_PIN_MUX_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "pinmux.h"
#include "csl_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define PIN_MODE(mode)	                (mode)
#define PINMUX_END                      (-1)

/** \brief Active mode configurations */
/** \brief Resistor disable */
#define PIN_PULL_DISABLE                (0x1U << 8U)  
/** \brief Pull direction */
#define	PIN_PULL_DIRECTION              (0x1U << 9U)


/** \brief Pad config register offset in control module */
enum pinOffsets
{
    PADAA_CFG_REG        = 0x0000U,
    PADAB_CFG_REG        = 0x0004U,
    PADAC_CFG_REG        = 0x0008U,
    PADAD_CFG_REG        = 0x000CU,
    PADAE_CFG_REG        = 0x0010U,
    PADAF_CFG_REG        = 0x0014U,
    PADAG_CFG_REG        = 0x0018U,
    PADAH_CFG_REG        = 0x001CU,
    PADAI_CFG_REG        = 0x0020U,
    PADAJ_CFG_REG        = 0x0024U,
    PADAK_CFG_REG        = 0x0028U,
    PADAL_CFG_REG        = 0x002CU,
    PADAM_CFG_REG        = 0x0030U,
    PADAN_CFG_REG        = 0x0034U,
    PADAO_CFG_REG        = 0x0038U,
    PADAP_CFG_REG        = 0x003CU,
    PADAQ_CFG_REG        = 0x0040U,
    PADAR_CFG_REG        = 0x0044U,
    PADAS_CFG_REG        = 0x0048U,
    PADAT_CFG_REG        = 0x004CU,
    PADAU_CFG_REG        = 0x0050U,
    PADAV_CFG_REG        = 0x0054U,
    PADAW_CFG_REG        = 0x0058U,
    PADAX_CFG_REG        = 0x005CU,
    PADAY_CFG_REG        = 0x0060U,
    PADAZ_CFG_REG        = 0x0064U,
    PADBA_CFG_REG        = 0x0068U,
    PADBB_CFG_REG        = 0x006CU,
    PADBC_CFG_REG        = 0x0070U,
    PADBD_CFG_REG        = 0x0074U,
    PADBE_CFG_REG        = 0x0078U,
    PADBF_CFG_REG        = 0x007CU,
    PADBG_CFG_REG        = 0x0080U,
    PADBH_CFG_REG        = 0x0084U,
    PADBI_CFG_REG        = 0x0088U,
    PADBJ_CFG_REG        = 0x008CU,
    PADBK_CFG_REG        = 0x0090U,
    PADBL_CFG_REG        = 0x0094U,
    PADBM_CFG_REG        = 0x0098U,
    PADBN_CFG_REG        = 0x009CU,
    PADBO_CFG_REG        = 0x00A0U,
    PADBP_CFG_REG        = 0x00A4U,
    PADBQ_CFG_REG        = 0x00A8U,
    PADBR_CFG_REG        = 0x00ACU,
    PADBS_CFG_REG        = 0x00B0U,
    PADBT_CFG_REG        = 0x00B4U,
    PADBU_CFG_REG        = 0x00B8U,
    PADBV_CFG_REG        = 0x00BCU,
    PADBW_CFG_REG        = 0x00C0U,
    PADBX_CFG_REG        = 0x00C4U,
    PADBY_CFG_REG        = 0x00C8U,
    PADBZ_CFG_REG        = 0x00CCU,
    PADCA_CFG_REG        = 0x00D0U,
    PADCB_CFG_REG        = 0x00D4U,
    PADCC_CFG_REG        = 0x00D8U,
    PADCD_CFG_REG        = 0x00DCU,
    PADCE_CFG_REG        = 0x00E0U,
    PADCF_CFG_REG        = 0x00E4U,
    PADCG_CFG_REG        = 0x00E8U,
    PADCH_CFG_REG        = 0x00ECU,
    PADCI_CFG_REG        = 0x00F0U,
    PADCJ_CFG_REG        = 0x00F4U,
    PADCK_CFG_REG        = 0x00F8U,
    PADCL_CFG_REG        = 0x00FCU,
    PADCM_CFG_REG        = 0x0100U,
    PADCN_CFG_REG        = 0x0104U,
    PADCO_CFG_REG        = 0x0108U,
    PADCP_CFG_REG        = 0x010CU,
    PADCQ_CFG_REG        = 0x0110U,
    PADCR_CFG_REG        = 0x0114U,
    PADCS_CFG_REG        = 0x0118U,
    PADCT_CFG_REG        = 0x011CU,
    PADCU_CFG_REG        = 0x0120U,
    PADCV_CFG_REG        = 0x0124U,
    PADCW_CFG_REG        = 0x0128U,
    PADCX_CFG_REG        = 0x012CU,
    PADCY_CFG_REG        = 0x0130U,
    PADCZ_CFG_REG        = 0x0134U,
    PADDA_CFG_REG        = 0x0138U,
    PADDB_CFG_REG        = 0x013CU,
    PADDC_CFG_REG        = 0x0140U,
    PADDD_CFG_REG        = 0x0144U,
    PADDE_CFG_REG        = 0x0148U,
    PADDF_CFG_REG        = 0x014CU,
    PADDG_CFG_REG        = 0x0150U,
    PADDH_CFG_REG        = 0x0154U,
    PADDI_CFG_REG        = 0x0158U,
    PADDJ_CFG_REG        = 0x015CU,
    PADDK_CFG_REG        = 0x0160U,
    PADDL_CFG_REG        = 0x0164U,
    PADDM_CFG_REG        = 0x0168U,
    PADDN_CFG_REG        = 0x016CU,
    PADDO_CFG_REG        = 0x0170U,
    PADDP_CFG_REG        = 0x0174U,
    PADDQ_CFG_REG        = 0x0178U,
    PADDR_CFG_REG        = 0x017CU,
    PADDS_CFG_REG        = 0x0180U,
    PADDT_CFG_REG        = 0x0184U,
    PADDU_CFG_REG        = 0x0188U,
    PADDV_CFG_REG        = 0x018CU,
    PADDW_CFG_REG        = 0x0190U,
    PADDX_CFG_REG        = 0x0194U,
    PADDY_CFG_REG        = 0x0198U,
    PADDZ_CFG_REG        = 0x019CU,
};

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Pinmux configuration data for the board. Auto-generated from 
           Pinmux tool. */
extern pinmuxBoardCfg_t gTPR12PinmuxData[];

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _TPR12EVM_PIN_MUX_H_ */
