/**
* Note: This file was auto-generated by TI PinMux on 4/23/2020 at 10:03:11 AM.
*
* \file  TPR12_evm_pinmux.c
*
* \brief  This file contains the pin mux configurations for the boards.
*         These are prepared based on how the peripherals are extended on
*         the boards.
*
* \copyright Copyright (CU) 2020 Texas Instruments Incorporated -
*             http://www.ti.com/
*/

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "TPR12_pinmux.h"

/** Peripheral Pin Configurations */

static pinmuxPerCfg_t gDss_uart0PinCfg[] =
{
    /* MyDSS_UART1 -> DSS_UARTA_TX -> J19 */
    {
        PIN_GP46, PIN_MODE(4) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyDSS_UART1 -> DSS_UARTA_RX -> H19 */
    {
        PIN_GP47, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gDss_uartPinCfg[] =
{
    {0, TRUE, gDss_uart0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gError0PinCfg[] =
{
    /* MyERROR1 -> NERROR_IN -> L3 */
    {
        PIN_NERRORIN, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyERROR1 -> WARM_RESET -> K1 */
    {
        PIN_WARMRESET, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyERROR1 -> NERROR_OUT -> L1 */
    {
        PIN_NERROROUT, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gErrorPinCfg[] =
{
    {0, TRUE, gError0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gFe1_refclk0PinCfg[] =
{
    /* MyFE1_REFCLK1 -> FE1_REFCLK -> H1 */
    {
        PIN_GP13, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gFe1_refclkPinCfg[] =
{
    {0, TRUE, gFe1_refclk0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gFe2_refclk0PinCfg[] =
{
    /* MyFE2_REFCLK1 -> FE2_REFCLK -> J2 */
    {
        PIN_GP16, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gFe2_refclkPinCfg[] =
{
    {0, TRUE, gFe2_refclk0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gGpio9PinCfg[] =
{
    /* MyGPIO49 -> RCSS_GPIO_49 -> E19 */
    {
        PIN_GP49, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPIO9 -> MSS_GPIO_9 -> B19 */
    {
        PIN_GP9(2), PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gGpio8PinCfg[] =
{
    /* MyGPIO28 -> MSS_GPIO_28 -> G3 */
    {
        PIN_GP28, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPIO8 -> MSS_GPIO_8 -> B3 */
    {
        PIN_GP8(2), PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gGpio2PinCfg[] =
{
    /* MyGPIO2 -> MSS_GPIO_2 -> H2 */
    {
        PIN_GP26, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyGPIO12 -> MSS_GPIO_12 -> A18 */
    {
        PIN_GP12(2), PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gGpio0PinCfg[] =
{
    /* MyGPIO10 -> MSS_GPIO_10 -> B18 */
    {
        PIN_GP10(2), PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gGpio1PinCfg[] =
{
    /* MyGPIO11 -> MSS_GPIO_11 -> C17 */
    {
        PIN_GP11(2), PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gGpio3PinCfg[] =
{
    /* MyGPIO13 -> MSS_GPIO_13 -> B17 */
    {
        PIN_GP13(2), PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gGpioPinCfg[] =
{
    {9, TRUE, gGpio9PinCfg},
    {8, TRUE, gGpio8PinCfg},
    {2, TRUE, gGpio2PinCfg},
    {0, TRUE, gGpio0PinCfg},
    {1, TRUE, gGpio1PinCfg},
    {3, TRUE, gGpio3PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gHw_sync_fe10PinCfg[] =
{
    /* MyHW_SYNC_FE11 -> HW_SYNC_FE1 -> V17 */
    {
        PIN_GP42, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gHw_sync_fe1PinCfg[] =
{
    {0, TRUE, gHw_sync_fe10PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gHw_sync_fe20PinCfg[] =
{
    /* MyHW_SYNC_FE21 -> HW_SYNC_FE2 -> W17 */
    {
        PIN_GP43, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gHw_sync_fe2PinCfg[] =
{
    {0, TRUE, gHw_sync_fe20PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gJtag0PinCfg[] =
{
    /* MyJTAG1 -> TCK -> C3 */
    {
        PIN_GP17, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyJTAG1 -> TMS -> D4 */
    {
        PIN_GP18, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyJTAG1 -> TDI -> C5 */
    {
        PIN_GP23, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyJTAG1 -> TDO -> D6 */
    {
        PIN_GP24, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gJtagPinCfg[] =
{
    {0, TRUE, gJtag0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_epwm0PinCfg[] =
{
    /* MyMSS_EPWM1 -> MSS_EPWMA0 -> E3 */
    {
        PIN_GP25, PIN_MODE(18) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_epwmPinCfg[] =
{
    {0, TRUE, gMss_epwm0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_i2c0PinCfg[] =
{
    /* MyMSS_I2C1 -> MSS_I2CA_SCL -> F18 */
    {
        PIN_GP51, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_I2C1 -> MSS_I2CA_SDA -> F16 */
    {
        PIN_GP50, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_i2cPinCfg[] =
{
    {0, TRUE, gMss_i2c0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_mcan0PinCfg[] =
{
    /* MyMSS_MCAN1 -> MSS_MCANB_RX -> B2 */
    {
        PIN_GP3, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MCAN1 -> MSS_MCANB_TX -> A2 */
    {
        PIN_GP30, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MCAN2 -> MSS_MCANA_RX -> C1 */
    {
        PIN_GP19, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MCAN2 -> MSS_MCANA_TX -> B1 */
    {
        PIN_GP20, PIN_MODE(2) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_mcanPinCfg[] =
{
    {0, TRUE, gMss_mcan0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_mdio0PinCfg[] =
{
    /* MyMSS_MDIO1 -> MSS_MDIO_DATA -> P19 */
    {
        PIN_GP30(2), PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MDIO1 -> MSS_MDIO_CLK -> R19 */
    {
        PIN_GP31, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_mdioPinCfg[] =
{
    {0, TRUE, gMss_mdio0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_mibspi0PinCfg[] =
{
    /* MyMSS_MIBSPI1 -> MSS_MIBSPIB_CS1 -> E18 */
    {
        PIN_GP12, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI1 -> MSS_MIBSPIB_CS2 -> E17 */
    {
        PIN_GP29, PIN_MODE(17) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI1 -> MSS_MIBSPIB_MOSI -> C18 */
    {
        PIN_GP21, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI1 -> MSS_MIBSPIB_MISO -> C19 */
    {
        PIN_GP22, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI1 -> MSS_MIBSPIB_CLK -> D18 */
    {
        PIN_GP5, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI1 -> MSS_MIBSPIB_CS0 -> D19 */
    {
        PIN_GP4, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI2 -> MSS_MIBSPIA_HOSTIRQ -> G18 */
    {
        PIN_GP7(2), PIN_MODE(16) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI2 -> MSS_MIBSPIA_MOSI -> H18 */
    {
        PIN_GP3(2), PIN_MODE(16) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI2 -> MSS_MIBSPIA_MISO -> G17 */
    {
        PIN_GP4(2), PIN_MODE(16) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI2 -> MSS_MIBSPIA_CLK -> G19 */
    {
        PIN_GP5(2), PIN_MODE(16) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_MIBSPI2 -> MSS_MIBSPIA_CS0 -> F19 */
    {
        PIN_GP6(2), PIN_MODE(16) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_mibspiPinCfg[] =
{
    {0, TRUE, gMss_mibspi0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_qspi0PinCfg[] =
{
    /* MyMSS_QSPI1 -> MSS_QSPI_0 -> C2 */
    {
        PIN_GP8, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_QSPI1 -> MSS_QSPI_1 -> D2 */
    {
        PIN_GP9, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_QSPI1 -> MSS_QSPI_2 -> D1 */
    {
        PIN_GP10, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_QSPI1 -> MSS_QSPI_3 -> E2 */
    {
        PIN_GP11, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_QSPI1 -> MSS_QSPI_CLK -> E1 */
    {
        PIN_GP7, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_QSPI1 -> MSS_QSPI_CS -> F2 */
    {
        PIN_GP6, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_qspiPinCfg[] =
{
    {0, TRUE, gMss_qspi0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_rgmii0PinCfg[] =
{
    /* MyMSS_RGMII1 -> MSS_RGMII_TCTL -> J18 */
    {
        PIN_GP52, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_RCTL -> J17 */
    {
        PIN_GP53, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_TD3 -> K18 */
    {
        PIN_GP54, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_TD2 -> K16 */
    {
        PIN_GP55, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_TD1 -> L17 */
    {
        PIN_GP56, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_TD0 -> L18 */
    {
        PIN_GP57, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_TCLK -> K19 */
    {
        PIN_GP58, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_RCLK -> M19 */
    {
        PIN_GP59, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_RD3 -> L19 */
    {
        PIN_GP60, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_RD2 -> M18 */
    {
        PIN_GP61, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_RD1 -> N19 */
    {
        PIN_GP62, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RGMII1 -> MSS_RGMII_RD0 -> P18 */
    {
        PIN_GP63, PIN_MODE(3) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_rgmiiPinCfg[] =
{
    {0, TRUE, gMss_rgmii0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_rs2320PinCfg[] =
{
    /* MyMSS_RS2321 -> MSS_RS232_RX -> G2 */
    {
        PIN_GP15, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_RS2321 -> MSS_RS232_TX -> G1 */
    {
        PIN_GP14, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_rs232PinCfg[] =
{
    {0, TRUE, gMss_rs2320PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMss_uart0PinCfg[] =
{
    /* MyMSS_UART1 -> MSS_UARTA_RX -> U3 */
    {
        PIN_GP44, PIN_MODE(5) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_UART1 -> MSS_UARTA_TX -> W2 */
    {
        PIN_GP45, PIN_MODE(5) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyMSS_UART2 -> MSS_UARTB_TX -> V9 */
    {
        PIN_GP0, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMss_uartPinCfg[] =
{
    {0, TRUE, gMss_uart0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gPmic_clkout0PinCfg[] =
{
    /* MyPMIC_CLKOUT1 -> PMIC_CLKOUT -> F1 */
    {
        PIN_GP27, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gPmic_clkoutPinCfg[] =
{
    {0, TRUE, gPmic_clkout0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gRcss_mibspi0PinCfg[] =
{
    /* MyRCSS_MIBSPI1 -> RCSS_MIBSPIA_MOSI -> R18 */
    {
        PIN_GP32, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI1 -> RCSS_MIBSPIA_MISO -> R17 */
    {
        PIN_GP33, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI1 -> RCSS_MIBSPIA_CLK -> T18 */
    {
        PIN_GP34, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI1 -> RCSS_MIBSPIA_CS0 -> T19 */
    {
        PIN_GP35, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI2 -> RCSS_MIBSPIB_MOSI -> U19 */
    {
        PIN_GP37, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI2 -> RCSS_MIBSPIB_MISO -> V18 */
    {
        PIN_GP38, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI2 -> RCSS_MIBSPIB_CLK -> V19 */
    {
        PIN_GP39, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_MIBSPI2 -> RCSS_MIBSPIB_CS0 -> U17 */
    {
        PIN_GP40, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gRcss_mibspiPinCfg[] =
{
    {0, TRUE, gRcss_mibspi0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gRcss_uart0PinCfg[] =
{
    /* MyRCSS_UART1 -> RCSS_UARTA_RX -> B16 */
    {
        PIN_GP15(2), PIN_MODE(2) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyRCSS_UART1 -> RCSS_UARTA_TX -> A17 */
    {
        PIN_GP14(2), PIN_MODE(2) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gRcss_uartPinCfg[] =
{
    {0, TRUE, gRcss_uart0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gTrace0PinCfg[] =
{
    /* MyTRACE1 -> TRACE_DATA_0 -> V16 */
    {
        PIN_TRACEDATA0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_1 -> U15 */
    {
        PIN_TRACEDATA1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_2 -> W16 */
    {
        PIN_TRACEDATA2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_3 -> V15 */
    {
        PIN_TRACEDATA3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_4 -> W15 */
    {
        PIN_TRACEDATA4, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_5 -> V14 */
    {
        PIN_TRACEDATA5, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_6 -> U13 */
    {
        PIN_TRACEDATA6, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_7 -> W14 */
    {
        PIN_TRACEDATA7, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_8 -> V13 */
    {
        PIN_TRACEDATA8, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_9 -> W13 */
    {
        PIN_TRACEDATA9, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_10 -> U11 */
    {
        PIN_TRACEDATA10, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_11 -> V11 */
    {
        PIN_TRACEDATA11, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_12 -> W11 */
    {
        PIN_TRACEDATA12, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_13 -> V10 */
    {
        PIN_TRACEDATA13, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_14 -> W10 */
    {
        PIN_TRACEDATA14, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_DATA_15 -> T10 */
    {
        PIN_TRACEDATA15, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_CLK -> W12 */
    {
        PIN_TRACECLK, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MyTRACE1 -> TRACE_CTL -> V12 */
    {
        PIN_TRACECTL, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gTracePinCfg[] =
{
    {0, TRUE, gTrace0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gXref_clk00PinCfg[] =
{
    /* MyXREF_CLK01 -> XREF_CLK0 -> J1 */
    {
        PIN_GP1, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gXref_clk0PinCfg[] =
{
    {0, TRUE, gXref_clk00PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gXref_clk10PinCfg[] =
{
    /* MyXREF_CLK11 -> XREF_CLK1 -> K2 */
    {
        PIN_GP2, PIN_MODE(1) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gXref_clk1PinCfg[] =
{
    {0, TRUE, gXref_clk10PinCfg},
    {PINMUX_END}
};


pinmuxBoardCfg_t gTPR12PinmuxData[] =
{
    {0, gDss_uartPinCfg},
    {1, gErrorPinCfg},
    {2, gFe1_refclkPinCfg},
    {3, gFe2_refclkPinCfg},
    {4, gGpioPinCfg},
    {5, gHw_sync_fe1PinCfg},
    {6, gHw_sync_fe2PinCfg},
    {7, gJtagPinCfg},
    {8, gMss_epwmPinCfg},
    {9, gMss_i2cPinCfg},
    {10, gMss_mcanPinCfg},
    {11, gMss_mdioPinCfg},
    {12, gMss_mibspiPinCfg},
    {13, gMss_qspiPinCfg},
    {14, gMss_rgmiiPinCfg},
    {15, gMss_rs232PinCfg},
    {16, gMss_uartPinCfg},
    {17, gPmic_clkoutPinCfg},
    {18, gRcss_mibspiPinCfg},
    {19, gRcss_uartPinCfg},
    {20, gTracePinCfg},
    {21, gXref_clk0PinCfg},
    {22, gXref_clk1PinCfg},
    {PINMUX_END}
};
