/*
 * Copyright (c) 2020, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * \file sciserver_secproxyConfigData.c
 *
 * \brief Private include file for secure proxy configuration
 */

#include <stdint.h>
#include <types/errno.h>
#include "sciserver_commMemorySoc.h"
#include <hosts.h>
#include "sciserver_secproxyConfigData.h"
#include "sciserver_ringAcelConfigData.h"

#include "sciserver_secproxyDescription.h"
#include "sciserver_secproxySocData.h"
#include "sciserver_ringAcelSocData.h"

/** SAFE_EVENT Does NOT generate an IRQ or an event onto ETL */
#define SOC_SAFE_EVENT (0xFFFFU)

const uint16_t Sciserver_SecureProxyTxConfigNum = SOC_MAX_SPT_TX_CONFIG_INSTANCES;

const struct Sciserver_SecureProxyTxThreadConfig Sciserver_SecureProxyTxConfigurations[SOC_MAX_SPT_TX_CONFIG_INSTANCES] = {
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_A72_0_NOTIFY_TX_THR156_CONF000] =           {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 156U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_0_NOTIFY_THR000_CONF006,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_A72_0_RESPONSE_TX_THR155_CONF001] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 155U,
        .num_credits        = 30U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_0_RESPONSE_THR001_CONF007,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_A72_1_NOTIFY_TX_THR154_CONF002] =           {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 154U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_1_NOTIFY_THR005_CONF008,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_A72_1_RESPONSE_TX_THR153_CONF003] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 153U,
        .num_credits        = 30U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_1_RESPONSE_THR006_CONF009,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_C7X_0_NOTIFY_TX_THR152_CONF004] =           {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 152U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C7X_0_NOTIFY_THR025_CONF016,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_C7X_0_RESPONSE_TX_THR151_CONF005] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 151U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C7X_0_RESPONSE_THR026_CONF017,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_C6X_0_0_NOTIFY_TX_THR150_CONF006] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 150U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_0_NOTIFY_THR035_CONF020,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_C6X_0_0_RESPONSE_TX_THR149_CONF007] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 149U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_0_RESPONSE_THR036_CONF021,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_C6X_1_0_NOTIFY_TX_THR148_CONF008] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 148U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_0_NOTIFY_THR045_CONF024,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_C6X_1_0_RESPONSE_TX_THR147_CONF009] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 147U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_0_RESPONSE_THR046_CONF025,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_0_R5_1_NOTIFY_TX_THR146_CONF010] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 146U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_1_NOTIFY_THR065_CONF032,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_0_R5_1_RESPONSE_TX_THR145_CONF011] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 145U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_1_RESPONSE_THR066_CONF033,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_0_R5_3_NOTIFY_TX_THR144_CONF012] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 144U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_3_NOTIFY_THR075_CONF036,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_0_R5_3_RESPONSE_TX_THR143_CONF013] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 143U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_3_RESPONSE_THR076_CONF037,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_1_R5_1_NOTIFY_TX_THR142_CONF014] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 142U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_1_NOTIFY_THR085_CONF040,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_1_R5_1_RESPONSE_TX_THR141_CONF015] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 141U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_1_RESPONSE_THR086_CONF041,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_1_R5_3_NOTIFY_TX_THR140_CONF016] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 140U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_3_NOTIFY_THR095_CONF044,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DMSC_SEC_MAIN_1_R5_3_RESPONSE_TX_THR139_CONF017] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 139U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_3_RESPONSE_THR096_CONF045,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_A72_2_NOTIFY_TX_THR135_CONF018] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 135U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_2_NOTIFY_THR010_CONF010,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_A72_2_RESPONSE_TX_THR134_CONF019] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 134U,
        .num_credits        = 22U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_2_RESPONSE_THR011_CONF011,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_A72_3_NOTIFY_TX_THR133_CONF020] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 133U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_3_NOTIFY_THR015_CONF012,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_A72_3_RESPONSE_TX_THR132_CONF021] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 132U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_3_RESPONSE_THR016_CONF013,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_A72_4_NOTIFY_TX_THR131_CONF022] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 131U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_4_NOTIFY_THR020_CONF014,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_A72_4_RESPONSE_TX_THR130_CONF023] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 130U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_A72_4_RESPONSE_THR021_CONF015,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_C7X_1_NOTIFY_TX_THR129_CONF024] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 129U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C7X_1_NOTIFY_THR030_CONF018,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_C7X_1_RESPONSE_TX_THR128_CONF025] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 128U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C7X_1_RESPONSE_THR031_CONF019,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_C6X_0_1_NOTIFY_TX_THR127_CONF026] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 127U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_1_NOTIFY_THR040_CONF022,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_C6X_0_1_RESPONSE_TX_THR126_CONF027] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 126U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_1_RESPONSE_THR041_CONF023,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_C6X_1_1_NOTIFY_TX_THR125_CONF028] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 125U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_1_NOTIFY_THR050_CONF026,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_C6X_1_1_RESPONSE_TX_THR124_CONF029] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 124U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_1_RESPONSE_THR051_CONF027,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_GPU_0_NOTIFY_TX_THR123_CONF030] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 123U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_GPU_0_NOTIFY_THR055_CONF028,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_GPU_0_RESPONSE_TX_THR122_CONF031] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 122U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_GPU_0_RESPONSE_THR056_CONF029,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_0_R5_0_NOTIFY_TX_THR121_CONF032] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 121U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_0_NOTIFY_THR060_CONF030,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_0_R5_0_RESPONSE_TX_THR120_CONF033] =   {
        .host_id        = HOST_ID_DM,
        .thread_id        = 120U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_0_RESPONSE_THR061_CONF031,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_0_R5_2_NOTIFY_TX_THR119_CONF034] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 119U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_2_NOTIFY_THR070_CONF034,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_0_R5_2_RESPONSE_TX_THR118_CONF035] =   {
        .host_id        = HOST_ID_DM,
        .thread_id        = 118U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_2_RESPONSE_THR071_CONF035,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_1_R5_0_NOTIFY_TX_THR117_CONF036] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 117U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_0_NOTIFY_THR080_CONF038,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_1_R5_0_RESPONSE_TX_THR116_CONF037] =   {
        .host_id        = HOST_ID_DM,
        .thread_id        = 116U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_0_RESPONSE_THR081_CONF039,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_1_R5_2_NOTIFY_TX_THR115_CONF038] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 115U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_2_NOTIFY_THR090_CONF042,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_MAIN_1_R5_2_RESPONSE_TX_THR114_CONF039] =   {
        .host_id        = HOST_ID_DM,
        .thread_id        = 114U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_2_RESPONSE_THR091_CONF043,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_ICSSG_0_NOTIFY_TX_THR113_CONF040] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 113U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_ICSSG_0_NOTIFY_THR100_CONF046,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_DM_NONSEC_ICSSG_0_RESPONSE_TX_THR112_CONF041] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 112U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_ICSSG_0_RESPONSE_THR101_CONF047,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_0_HIGH_PRIORITY_THR002_CONF042] =           {
        .host_id        = HOST_ID_A72_0,
        .thread_id        = 2U,
        .num_credits        = 10U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_0_LOW_PRIORITY_THR003_CONF043] =           {
        .host_id        = HOST_ID_A72_0,
        .thread_id        = 3U,
        .num_credits        = 20U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_0_NOTIFY_RESP_THR004_CONF044] =           {
        .host_id        = HOST_ID_A72_0,
        .thread_id        = 4U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_1_HIGH_PRIORITY_THR007_CONF045] =           {
        .host_id        = HOST_ID_A72_1,
        .thread_id        = 7U,
        .num_credits        = 10U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_1_LOW_PRIORITY_THR008_CONF046] =           {
        .host_id        = HOST_ID_A72_1,
        .thread_id        = 8U,
        .num_credits        = 20U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_1_NOTIFY_RESP_THR009_CONF047] =           {
        .host_id        = HOST_ID_A72_1,
        .thread_id        = 9U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_2_HIGH_PRIORITY_THR012_CONF048] =           {
        .host_id        = HOST_ID_A72_2,
        .thread_id        = 12U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_2_LOW_PRIORITY_THR013_CONF049] =           {
        .host_id        = HOST_ID_A72_2,
        .thread_id        = 13U,
        .num_credits        = 20U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_2_NOTIFY_RESP_THR014_CONF050] =           {
        .host_id        = HOST_ID_A72_2,
        .thread_id        = 14U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_3_HIGH_PRIORITY_THR017_CONF051] =           {
        .host_id        = HOST_ID_A72_3,
        .thread_id        = 17U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_3_LOW_PRIORITY_THR018_CONF052] =           {
        .host_id        = HOST_ID_A72_3,
        .thread_id        = 18U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_3_NOTIFY_RESP_THR019_CONF053] =           {
        .host_id        = HOST_ID_A72_3,
        .thread_id        = 19U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_4_HIGH_PRIORITY_THR022_CONF054] =           {
        .host_id        = HOST_ID_A72_4,
        .thread_id        = 22U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_4_LOW_PRIORITY_THR023_CONF055] =           {
        .host_id        = HOST_ID_A72_4,
        .thread_id        = 23U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_A72_4_NOTIFY_RESP_THR024_CONF056] =           {
        .host_id        = HOST_ID_A72_4,
        .thread_id        = 24U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C7X_0_HIGH_PRIORITY_THR027_CONF057] =           {
        .host_id        = HOST_ID_C7X_0,
        .thread_id        = 27U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C7X_0_LOW_PRIORITY_THR028_CONF058] =           {
        .host_id        = HOST_ID_C7X_0,
        .thread_id        = 28U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C7X_0_NOTIFY_RESP_THR029_CONF059] =           {
        .host_id        = HOST_ID_C7X_0,
        .thread_id        = 29U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C7X_1_HIGH_PRIORITY_THR032_CONF060] =           {
        .host_id        = HOST_ID_C7X_1,
        .thread_id        = 32U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C7X_1_LOW_PRIORITY_THR033_CONF061] =           {
        .host_id        = HOST_ID_C7X_1,
        .thread_id        = 33U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C7X_1_NOTIFY_RESP_THR034_CONF062] =           {
        .host_id        = HOST_ID_C7X_1,
        .thread_id        = 34U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_0_0_HIGH_PRIORITY_THR037_CONF063] =           {
        .host_id        = HOST_ID_C6X_0_0,
        .thread_id        = 37U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_0_0_LOW_PRIORITY_THR038_CONF064] =           {
        .host_id        = HOST_ID_C6X_0_0,
        .thread_id        = 38U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_0_0_NOTIFY_RESP_THR039_CONF065] =           {
        .host_id        = HOST_ID_C6X_0_0,
        .thread_id        = 39U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_0_1_HIGH_PRIORITY_THR042_CONF066] =           {
        .host_id        = HOST_ID_C6X_0_1,
        .thread_id        = 42U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_0_1_LOW_PRIORITY_THR043_CONF067] =           {
        .host_id        = HOST_ID_C6X_0_1,
        .thread_id        = 43U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_0_1_NOTIFY_RESP_THR044_CONF068] =           {
        .host_id        = HOST_ID_C6X_0_1,
        .thread_id        = 44U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_1_0_HIGH_PRIORITY_THR047_CONF069] =           {
        .host_id        = HOST_ID_C6X_1_0,
        .thread_id        = 47U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_1_0_LOW_PRIORITY_THR048_CONF070] =           {
        .host_id        = HOST_ID_C6X_1_0,
        .thread_id        = 48U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_1_0_NOTIFY_RESP_THR049_CONF071] =           {
        .host_id        = HOST_ID_C6X_1_0,
        .thread_id        = 49U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_1_1_HIGH_PRIORITY_THR052_CONF072] =           {
        .host_id        = HOST_ID_C6X_1_1,
        .thread_id        = 52U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_1_1_LOW_PRIORITY_THR053_CONF073] =           {
        .host_id        = HOST_ID_C6X_1_1,
        .thread_id        = 53U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_C6X_1_1_NOTIFY_RESP_THR054_CONF074] =           {
        .host_id        = HOST_ID_C6X_1_1,
        .thread_id        = 54U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_GPU_0_HIGH_PRIORITY_THR057_CONF075] =           {
        .host_id        = HOST_ID_GPU_0,
        .thread_id        = 57U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_GPU_0_LOW_PRIORITY_THR058_CONF076] =           {
        .host_id        = HOST_ID_GPU_0,
        .thread_id        = 58U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_GPU_0_NOTIFY_RESP_THR059_CONF077] =           {
        .host_id        = HOST_ID_GPU_0,
        .thread_id        = 59U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_0_HIGH_PRIORITY_THR062_CONF078] =       {
        .host_id        = HOST_ID_MAIN_0_R5_0,
        .thread_id        = 62U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_0_LOW_PRIORITY_THR063_CONF079] =           {
        .host_id        = HOST_ID_MAIN_0_R5_0,
        .thread_id        = 63U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_0_NOTIFY_RESP_THR064_CONF080] =           {
        .host_id        = HOST_ID_MAIN_0_R5_0,
        .thread_id        = 64U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_1_HIGH_PRIORITY_THR067_CONF081] =       {
        .host_id        = HOST_ID_MAIN_0_R5_1,
        .thread_id        = 67U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_1_LOW_PRIORITY_THR068_CONF082] =           {
        .host_id        = HOST_ID_MAIN_0_R5_1,
        .thread_id        = 68U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_1_NOTIFY_RESP_THR069_CONF083] =           {
        .host_id        = HOST_ID_MAIN_0_R5_1,
        .thread_id        = 69U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_2_HIGH_PRIORITY_THR072_CONF084] =       {
        .host_id        = HOST_ID_MAIN_0_R5_2,
        .thread_id        = 72U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_2_LOW_PRIORITY_THR073_CONF085] =           {
        .host_id        = HOST_ID_MAIN_0_R5_2,
        .thread_id        = 73U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_2_NOTIFY_RESP_THR074_CONF086] =           {
        .host_id        = HOST_ID_MAIN_0_R5_2,
        .thread_id        = 74U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_3_HIGH_PRIORITY_THR077_CONF087] =       {
        .host_id        = HOST_ID_MAIN_0_R5_3,
        .thread_id        = 77U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_3_LOW_PRIORITY_THR078_CONF088] =           {
        .host_id        = HOST_ID_MAIN_0_R5_3,
        .thread_id        = 78U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_0_R5_3_NOTIFY_RESP_THR079_CONF089] =           {
        .host_id        = HOST_ID_MAIN_0_R5_3,
        .thread_id        = 79U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_0_HIGH_PRIORITY_THR082_CONF090] =       {
        .host_id        = HOST_ID_MAIN_1_R5_0,
        .thread_id        = 82U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_0_LOW_PRIORITY_THR083_CONF091] =           {
        .host_id        = HOST_ID_MAIN_1_R5_0,
        .thread_id        = 83U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_0_NOTIFY_RESP_THR084_CONF092] =           {
        .host_id        = HOST_ID_MAIN_1_R5_0,
        .thread_id        = 84U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_1_HIGH_PRIORITY_THR087_CONF093] =       {
        .host_id        = HOST_ID_MAIN_1_R5_1,
        .thread_id        = 87U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_1_LOW_PRIORITY_THR088_CONF094] =           {
        .host_id        = HOST_ID_MAIN_1_R5_1,
        .thread_id        = 88U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_1_NOTIFY_RESP_THR089_CONF095] =           {
        .host_id        = HOST_ID_MAIN_1_R5_1,
        .thread_id        = 89U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_2_HIGH_PRIORITY_THR092_CONF096] =       {
        .host_id        = HOST_ID_MAIN_1_R5_2,
        .thread_id        = 92U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_2_LOW_PRIORITY_THR093_CONF097] =           {
        .host_id        = HOST_ID_MAIN_1_R5_2,
        .thread_id        = 93U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_2_NOTIFY_RESP_THR094_CONF098] =           {
        .host_id        = HOST_ID_MAIN_1_R5_2,
        .thread_id        = 94U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_3_HIGH_PRIORITY_THR097_CONF099] =       {
        .host_id        = HOST_ID_MAIN_1_R5_3,
        .thread_id        = 97U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_3_LOW_PRIORITY_THR098_CONF100] =           {
        .host_id        = HOST_ID_MAIN_1_R5_3,
        .thread_id        = 98U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_MAIN_1_R5_3_NOTIFY_RESP_THR099_CONF101] =           {
        .host_id        = HOST_ID_MAIN_1_R5_3,
        .thread_id        = 99U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_ICSSG_0_HIGH_PRIORITY_THR102_CONF102] =           {
        .host_id        = HOST_ID_ICSSG_0,
        .thread_id        = 102U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_ICSSG_0_LOW_PRIORITY_THR103_CONF103] =           {
        .host_id        = HOST_ID_ICSSG_0,
        .thread_id        = 103U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_TX_ICSSG_0_NOTIFY_RESP_THR104_CONF104] =           {
        .host_id        = HOST_ID_ICSSG_0,
        .thread_id        = 104U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC_SEC_MCU_0_R5_1_NOTIFY_TX_THR086_CONF105] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 86U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_1_NOTIFY_THR005_CONF056,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC_SEC_MCU_0_R5_1_RESPONSE_TX_THR085_CONF106] =  {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 85U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_1_RESPONSE_THR006_CONF057,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC_SEC_MCU_0_R5_3_NOTIFY_TX_THR084_CONF107] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 84U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_3_NOTIFY_THR015_CONF060,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC_SEC_MCU_0_R5_3_RESPONSE_TX_THR083_CONF108] =  {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 83U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_3_RESPONSE_THR016_CONF061,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC_SEC_DM2DMSC_NOTIFY_TX_THR082_CONF109] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 82U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM2DMSC_NOTIFY_THR020_CONF062,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC_SEC_DM2DMSC_RESPONSE_TX_THR081_CONF110] =       {
        .host_id        = HOST_ID_DMSC,
        .thread_id        = 81U,
        .num_credits        = 4U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM2DMSC_RESPONSE_THR021_CONF063,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM_NONSEC_MCU_0_R5_0_NOTIFY_TX_THR077_CONF111] =   {
        .host_id        = HOST_ID_DM,
        .thread_id        = 77U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_0_NOTIFY_THR000_CONF054,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM_NONSEC_MCU_0_R5_0_RESPONSE_TX_THR076_CONF112] = {
        .host_id        = HOST_ID_DM,
        .thread_id        = 76U,
        .num_credits        = 7U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_0_RESPONSE_THR001_CONF055,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM_NONSEC_MCU_0_R5_2_NOTIFY_TX_THR075_CONF113] =   {
        .host_id        = HOST_ID_DM,
        .thread_id        = 75U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_2_NOTIFY_THR010_CONF058,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM_NONSEC_MCU_0_R5_2_RESPONSE_TX_THR074_CONF114] = {
        .host_id        = HOST_ID_DM,
        .thread_id        = 74U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_2_RESPONSE_THR011_CONF059,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM_NONSEC_DMSC2DM_NOTIFY_TX_THR073_CONF115] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 73U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC2DM_NOTIFY_THR025_CONF064,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM_NONSEC_DMSC2DM_RESPONSE_TX_THR072_CONF116] =       {
        .host_id        = HOST_ID_DM,
        .thread_id        = 72U,
        .num_credits        = 4U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC2DM_RESPONSE_THR026_CONF065,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_0_HIGH_PRIORITY_THR002_CONF117] =       {
        .host_id        = HOST_ID_MCU_0_R5_0,
        .thread_id        = 2U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR080_CONF051,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_0_LOW_PRIORITY_THR003_CONF118] =       {
        .host_id        = HOST_ID_MCU_0_R5_0,
        .thread_id        = 3U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR079_CONF052,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_0_NOTIFY_RESP_THR004_CONF119] =       {
        .host_id        = HOST_ID_MCU_0_R5_0,
        .thread_id        = 4U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR078_CONF053,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_1_HIGH_PRIORITY_THR007_CONF120] =       {
        .host_id        = HOST_ID_MCU_0_R5_1,
        .thread_id        = 7U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR089_CONF048,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_1_LOW_PRIORITY_THR008_CONF121] =       {
        .host_id        = HOST_ID_MCU_0_R5_1,
        .thread_id        = 8U,
        .num_credits        = 5U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR088_CONF049,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_1_NOTIFY_RESP_THR009_CONF122] =       {
        .host_id        = HOST_ID_MCU_0_R5_1,
        .thread_id        = 9U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR087_CONF050,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_2_HIGH_PRIORITY_THR012_CONF123] =       {
        .host_id        = HOST_ID_MCU_0_R5_2,
        .thread_id        = 12U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR080_CONF051,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_2_LOW_PRIORITY_THR013_CONF124] =       {
        .host_id        = HOST_ID_MCU_0_R5_2,
        .thread_id        = 13U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR079_CONF052,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_2_NOTIFY_RESP_THR014_CONF125] =       {
        .host_id        = HOST_ID_MCU_0_R5_2,
        .thread_id        = 14U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR078_CONF053,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_3_HIGH_PRIORITY_THR017_CONF126] =       {
        .host_id        = HOST_ID_MCU_0_R5_3,
        .thread_id        = 17U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR089_CONF048,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_3_LOW_PRIORITY_THR018_CONF127] =       {
        .host_id        = HOST_ID_MCU_0_R5_3,
        .thread_id        = 18U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR088_CONF049,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_MCU_0_R5_3_NOTIFY_RESP_THR019_CONF128] =       {
        .host_id        = HOST_ID_MCU_0_R5_3,
        .thread_id        = 19U,
        .num_credits        = 1U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR087_CONF050,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM2DMSC_HIGH_PRIORITY_THR022_CONF129] =           {
        .host_id        = HOST_ID_DM2DMSC,
        .thread_id        = 22U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR089_CONF048,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM2DMSC_LOW_PRIORITY_THR023_CONF130] =           {
        .host_id        = HOST_ID_DM2DMSC,
        .thread_id        = 23U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR088_CONF049,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DM2DMSC_NOTIFY_RESP_THR024_CONF131] =           {
        .host_id        = HOST_ID_DM2DMSC,
        .thread_id        = 24U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR087_CONF050,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC2DM_HIGH_PRIORITY_THR027_CONF132] =           {
        .host_id        = HOST_ID_DMSC2DM,
        .thread_id        = 27U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR080_CONF051,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC2DM_LOW_PRIORITY_THR028_CONF133] =           {
        .host_id        = HOST_ID_DMSC2DM,
        .thread_id        = 28U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR079_CONF052,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_TX_DMSC2DM_NOTIFY_RESP_THR029_CONF134] =           {
        .host_id        = HOST_ID_DMSC2DM,
        .thread_id        = 29U,
        .num_credits        = 2U,
        .threshold        = 1U,
        .evt_threshold        = SOC_SAFE_EVENT,
        .evt_error        = SOC_SAFE_EVENT,
        .rx_thread_instance_id    = J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR078_CONF053,
    },
};

const uint16_t gSciserverSecureProxyRxConfigNum = SOC_MAX_SPT_RX_CONFIG_INSTANCES;

const struct Sciserver_SecureProxyRxThreadConfig gSciserverSecureProxyRxConfigurations[SOC_MAX_SPT_RX_CONFIG_INSTANCES] = {
    [J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR159_CONF000] =     {
        .host_id            = HOST_ID_DMSC,
        .thread_id            = 159U,
        .threshold            = 1U,
        .evt_threshold            = 0x4802U,
        .evt_error            = 0x4800U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1023_CONF_000,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR158_CONF001] =         {
        .host_id            = HOST_ID_DMSC,
        .thread_id            = 158U,
        .threshold            = 1U,
        .evt_threshold            = 0x4804U,
        .evt_error            = 0x4800U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1022_CONF_001,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR157_CONF002] =         {
        .host_id            = HOST_ID_DMSC,
        .thread_id            = 157U,
        .threshold            = 1U,
        .evt_threshold            = 0x4806U,
        .evt_error            = 0x4800U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1021_CONF_002,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR138_CONF003] =    {
        .host_id            = HOST_ID_DM,
        .thread_id            = 138U,
        .threshold            = 1U,
        .evt_threshold            = 0x400AU,
        .evt_error            = 0x4008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1020_CONF_003,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR137_CONF004] =     {
        .host_id            = HOST_ID_DM,
        .thread_id            = 137U,
        .threshold            = 1U,
        .evt_threshold            = 0x400CU,
        .evt_error            = 0x4008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1019_CONF_004,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR136_CONF005] =         {
        .host_id            = HOST_ID_DM,
        .thread_id            = 136U,
        .threshold            = 1U,
        .evt_threshold            = 0x400EU,
        .evt_error            = 0x4008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1018_CONF_005,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_0_NOTIFY_THR000_CONF006] =             {
        .host_id            = HOST_ID_A72_0,
        .thread_id            = 0U,
        .threshold            = 1U,
        .evt_threshold            = 0x0000U,
        .evt_error            = 0x0000U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1017_CONF_006,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_0_RESPONSE_THR001_CONF007] =             {
        .host_id            = HOST_ID_A72_0,
        .thread_id            = 1U,
        .threshold            = 1U,
        .evt_threshold            = 0x0001U,
        .evt_error            = 0x0001U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1016_CONF_007,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_1_NOTIFY_THR005_CONF008] =             {
        .host_id            = HOST_ID_A72_1,
        .thread_id            = 5U,
        .threshold            = 1U,
        .evt_threshold            = 0x0002U,
        .evt_error            = 0x0002U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1015_CONF_008,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_1_RESPONSE_THR006_CONF009] =             {
        .host_id            = HOST_ID_A72_1,
        .thread_id            = 6U,
        .threshold            = 1U,
        .evt_threshold            = 0x0003U,
        .evt_error            = 0x0003U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1014_CONF_009,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_2_NOTIFY_THR010_CONF010] =             {
        .host_id            = HOST_ID_A72_2,
        .thread_id            = 10U,
        .threshold            = 1U,
        .evt_threshold            = 0x0004U,
        .evt_error            = 0x0004U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1013_CONF_010,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_2_RESPONSE_THR011_CONF011] =             {
        .host_id            = HOST_ID_A72_2,
        .thread_id            = 11U,
        .threshold            = 1U,
        .evt_threshold            = 0x0005U,
        .evt_error            = 0x0005U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1012_CONF_011,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_3_NOTIFY_THR015_CONF012] =             {
        .host_id            = HOST_ID_A72_3,
        .thread_id            = 15U,
        .threshold            = 1U,
        .evt_threshold            = 0x0006U,
        .evt_error            = 0x0006U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1011_CONF_012,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_3_RESPONSE_THR016_CONF013] =             {
        .host_id            = HOST_ID_A72_3,
        .thread_id            = 16U,
        .threshold            = 1U,
        .evt_threshold            = 0x0007U,
        .evt_error            = 0x0007U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1010_CONF_013,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_4_NOTIFY_THR020_CONF014] =             {
        .host_id            = HOST_ID_A72_4,
        .thread_id            = 20U,
        .threshold            = 1U,
        .evt_threshold            = 0x0008U,
        .evt_error            = 0x0008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1009_CONF_014,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_A72_4_RESPONSE_THR021_CONF015] =             {
        .host_id            = HOST_ID_A72_4,
        .thread_id            = 21U,
        .threshold            = 1U,
        .evt_threshold            = 0x0009U,
        .evt_error            = 0x0009U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1008_CONF_015,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C7X_0_NOTIFY_THR025_CONF016] =             {
        .host_id            = HOST_ID_C7X_0,
        .thread_id            = 25U,
        .threshold            = 1U,
        .evt_threshold            = 0x000AU,
        .evt_error            = 0x000AU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1007_CONF_016,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C7X_0_RESPONSE_THR026_CONF017] =             {
        .host_id            = HOST_ID_C7X_0,
        .thread_id            = 26U,
        .threshold            = 1U,
        .evt_threshold            = 0x000BU,
        .evt_error            = 0x000BU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1006_CONF_017,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C7X_1_NOTIFY_THR030_CONF018] =             {
        .host_id            = HOST_ID_C7X_1,
        .thread_id            = 30U,
        .threshold            = 1U,
        .evt_threshold            = 0x000CU,
        .evt_error            = 0x000CU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1005_CONF_018,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C7X_1_RESPONSE_THR031_CONF019] =             {
        .host_id            = HOST_ID_C7X_1,
        .thread_id            = 31U,
        .threshold            = 1U,
        .evt_threshold            = 0x000DU,
        .evt_error            = 0x000DU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1004_CONF_019,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_0_NOTIFY_THR035_CONF020] =             {
        .host_id            = HOST_ID_C6X_0_0,
        .thread_id            = 35U,
        .threshold            = 1U,
        .evt_threshold            = 0x000EU,
        .evt_error            = 0x000EU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1003_CONF_020,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_0_RESPONSE_THR036_CONF021] =             {
        .host_id            = HOST_ID_C6X_0_0,
        .thread_id            = 36U,
        .threshold            = 1U,
        .evt_threshold            = 0x000FU,
        .evt_error            = 0x000FU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1002_CONF_021,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_1_NOTIFY_THR040_CONF022] =             {
        .host_id            = HOST_ID_C6X_0_1,
        .thread_id            = 40U,
        .threshold            = 1U,
        .evt_threshold            = 0x0010U,
        .evt_error            = 0x0010U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1001_CONF_022,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_0_1_RESPONSE_THR041_CONF023] =             {
        .host_id            = HOST_ID_C6X_0_1,
        .thread_id            = 41U,
        .threshold            = 1U,
        .evt_threshold            = 0x0011U,
        .evt_error            = 0x0011U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_1000_CONF_023,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_0_NOTIFY_THR045_CONF024] =             {
        .host_id            = HOST_ID_C6X_1_0,
        .thread_id            = 45U,
        .threshold            = 1U,
        .evt_threshold            = 0x0012U,
        .evt_error            = 0x0012U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0999_CONF_024,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_0_RESPONSE_THR046_CONF025] =             {
        .host_id            = HOST_ID_C6X_1_0,
        .thread_id            = 46U,
        .threshold            = 1U,
        .evt_threshold            = 0x0013U,
        .evt_error            = 0x0013U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0998_CONF_025,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_1_NOTIFY_THR050_CONF026] =             {
        .host_id            = HOST_ID_C6X_1_1,
        .thread_id            = 50U,
        .threshold            = 1U,
        .evt_threshold            = 0x0014U,
        .evt_error            = 0x0014U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0997_CONF_026,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_C6X_1_1_RESPONSE_THR051_CONF027] =             {
        .host_id            = HOST_ID_C6X_1_1,
        .thread_id            = 51U,
        .threshold            = 1U,
        .evt_threshold            = 0x0015U,
        .evt_error            = 0x0015U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0996_CONF_027,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_GPU_0_NOTIFY_THR055_CONF028] =             {
        .host_id            = HOST_ID_GPU_0,
        .thread_id            = 55U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0995_CONF_028,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_GPU_0_RESPONSE_THR056_CONF029] =             {
        .host_id            = HOST_ID_GPU_0,
        .thread_id            = 56U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0994_CONF_029,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_0_NOTIFY_THR060_CONF030] =         {
        .host_id            = HOST_ID_MAIN_0_R5_0,
        .thread_id            = 60U,
        .threshold            = 1U,
        .evt_threshold            = 0x0016U,
        .evt_error            = 0x0016U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0993_CONF_030,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_0_RESPONSE_THR061_CONF031] =         {
        .host_id            = HOST_ID_MAIN_0_R5_0,
        .thread_id            = 61U,
        .threshold            = 1U,
        .evt_threshold            = 0x0017U,
        .evt_error            = 0x0017U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0992_CONF_031,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_1_NOTIFY_THR065_CONF032] =         {
        .host_id            = HOST_ID_MAIN_0_R5_1,
        .thread_id            = 65U,
        .threshold            = 1U,
        .evt_threshold            = 0x0018U,
        .evt_error            = 0x0018U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0991_CONF_032,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_1_RESPONSE_THR066_CONF033] =         {
        .host_id            = HOST_ID_MAIN_0_R5_1,
        .thread_id            = 66U,
        .threshold            = 1U,
        .evt_threshold            = 0x0019U,
        .evt_error            = 0x0019U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0990_CONF_033,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_2_NOTIFY_THR070_CONF034] =         {
        .host_id            = HOST_ID_MAIN_0_R5_2,
        .thread_id            = 70U,
        .threshold            = 1U,
        .evt_threshold            = 0x001AU,
        .evt_error            = 0x001AU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0989_CONF_034,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_2_RESPONSE_THR071_CONF035] =         {
        .host_id            = HOST_ID_MAIN_0_R5_2,
        .thread_id            = 71U,
        .threshold            = 1U,
        .evt_threshold            = 0x001BU,
        .evt_error            = 0x001BU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0988_CONF_035,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_3_NOTIFY_THR075_CONF036] =         {
        .host_id            = HOST_ID_MAIN_0_R5_3,
        .thread_id            = 75U,
        .threshold            = 1U,
        .evt_threshold            = 0x001CU,
        .evt_error            = 0x001CU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0987_CONF_036,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_0_R5_3_RESPONSE_THR076_CONF037] =         {
        .host_id            = HOST_ID_MAIN_0_R5_3,
        .thread_id            = 76U,
        .threshold            = 1U,
        .evt_threshold            = 0x001DU,
        .evt_error            = 0x001DU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0986_CONF_037,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_0_NOTIFY_THR080_CONF038] =         {
        .host_id            = HOST_ID_MAIN_1_R5_0,
        .thread_id            = 80U,
        .threshold            = 1U,
        .evt_threshold            = 0x001EU,
        .evt_error            = 0x001EU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0985_CONF_038,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_0_RESPONSE_THR081_CONF039] =         {
        .host_id            = HOST_ID_MAIN_1_R5_0,
        .thread_id            = 81U,
        .threshold            = 1U,
        .evt_threshold            = 0x001FU,
        .evt_error            = 0x001FU,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0984_CONF_039,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_1_NOTIFY_THR085_CONF040] =         {
        .host_id            = HOST_ID_MAIN_1_R5_1,
        .thread_id            = 85U,
        .threshold            = 1U,
        .evt_threshold            = 0x0020U,
        .evt_error            = 0x0020U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0983_CONF_040,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_1_RESPONSE_THR086_CONF041] =         {
        .host_id            = HOST_ID_MAIN_1_R5_1,
        .thread_id            = 86U,
        .threshold            = 1U,
        .evt_threshold            = 0x0021U,
        .evt_error            = 0x0021U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0982_CONF_041,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_2_NOTIFY_THR090_CONF042] =         {
        .host_id            = HOST_ID_MAIN_1_R5_2,
        .thread_id            = 90U,
        .threshold            = 1U,
        .evt_threshold            = 0x0022U,
        .evt_error            = 0x0022U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0981_CONF_042,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_2_RESPONSE_THR091_CONF043] =         {
        .host_id            = HOST_ID_MAIN_1_R5_2,
        .thread_id            = 91U,
        .threshold            = 1U,
        .evt_threshold            = 0x0023U,
        .evt_error            = 0x0023U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0980_CONF_043,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_3_NOTIFY_THR095_CONF044] =         {
        .host_id            = HOST_ID_MAIN_1_R5_3,
        .thread_id            = 95U,
        .threshold            = 1U,
        .evt_threshold            = 0x0024U,
        .evt_error            = 0x0024U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0979_CONF_044,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_MAIN_1_R5_3_RESPONSE_THR096_CONF045] =         {
        .host_id            = HOST_ID_MAIN_1_R5_3,
        .thread_id            = 96U,
        .threshold            = 1U,
        .evt_threshold            = 0x0025U,
        .evt_error            = 0x0025U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0978_CONF_045,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_ICSSG_0_NOTIFY_THR100_CONF046] =             {
        .host_id            = HOST_ID_ICSSG_0,
        .thread_id            = 100U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0977_CONF_046,
    },
    [J721E_NAVSS0_SEC_PROXY_0_RX_ICSSG_0_RESPONSE_THR101_CONF047] =             {
        .host_id            = HOST_ID_ICSSG_0,
        .thread_id            = 101U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_NAVSS0_SEC_PROXY_0,
        .ring_config_instance_id    = J721E_NAVSS0_RINGACC_0_RING_0976_CONF_047,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_HIGH_PRIORITY_RX_THR089_CONF048] =  {
        .host_id            = HOST_ID_DMSC,
        .thread_id            = 89U,
        .threshold            = 1U,
        .evt_threshold            = 0x4801U,
        .evt_error            = 0x4800U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0285_CONF_048,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_LOW_PRIORITY_RX_THR088_CONF049] =   {
        .host_id            = HOST_ID_DMSC,
        .thread_id            = 88U,
        .threshold            = 1U,
        .evt_threshold            = 0x4803U,
        .evt_error            = 0x4800U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0284_CONF_049,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC_SEC_NOTIFY_RESP_RX_THR087_CONF050] =    {
        .host_id            = HOST_ID_DMSC,
        .thread_id            = 87U,
        .threshold            = 1U,
        .evt_threshold            = 0x4805U,
        .evt_error            = 0x4800U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0283_CONF_050,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_HIGH_PRIORITY_RX_THR080_CONF051] = {
        .host_id            = HOST_ID_DM,
        .thread_id            = 80U,
        .threshold            = 1U,
        .evt_threshold            = 0x4009U,
        .evt_error            = 0x4008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0282_CONF_051,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_LOW_PRIORITY_RX_THR079_CONF052] =  {
        .host_id            = HOST_ID_DM,
        .thread_id            = 79U,
        .threshold            = 1U,
        .evt_threshold            = 0x400BU,
        .evt_error            = 0x4008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0281_CONF_052,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM_NONSEC_NOTIFY_RESP_RX_THR078_CONF053] =   {
        .host_id            = HOST_ID_DM,
        .thread_id            = 78U,
        .threshold            = 1U,
        .evt_threshold            = 0x400DU,
        .evt_error            = 0x4008U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0280_CONF_053,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_0_NOTIFY_THR000_CONF054] =         {
        .host_id            = HOST_ID_MCU_0_R5_0,
        .thread_id            = 0U,
        .threshold            = 1U,
        .evt_threshold            = 0x4000U,
        .evt_error            = 0x4000U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0279_CONF_054,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_0_RESPONSE_THR001_CONF055] =         {
        .host_id            = HOST_ID_MCU_0_R5_0,
        .thread_id            = 1U,
        .threshold            = 1U,
        .evt_threshold            = 0x4001U,
        .evt_error            = 0x4001U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0278_CONF_055,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_1_NOTIFY_THR005_CONF056] =         {
        .host_id            = HOST_ID_MCU_0_R5_1,
        .thread_id            = 5U,
        .threshold            = 1U,
        .evt_threshold            = 0x4002U,
        .evt_error            = 0x4002U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0277_CONF_056,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_1_RESPONSE_THR006_CONF057] =         {
        .host_id            = HOST_ID_MCU_0_R5_1,
        .thread_id            = 6U,
        .threshold            = 1U,
        .evt_threshold            = 0x4003U,
        .evt_error            = 0x4003U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0276_CONF_057,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_2_NOTIFY_THR010_CONF058] =         {
        .host_id            = HOST_ID_MCU_0_R5_2,
        .thread_id            = 10U,
        .threshold            = 1U,
        .evt_threshold            = 0x4004U,
        .evt_error            = 0x4004U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0275_CONF_058,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_2_RESPONSE_THR011_CONF059] =         {
        .host_id            = HOST_ID_MCU_0_R5_2,
        .thread_id            = 11U,
        .threshold            = 1U,
        .evt_threshold            = 0x4005U,
        .evt_error            = 0x4005U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0274_CONF_059,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_3_NOTIFY_THR015_CONF060] =         {
        .host_id            = HOST_ID_MCU_0_R5_3,
        .thread_id            = 15U,
        .threshold            = 1U,
        .evt_threshold            = 0x4006U,
        .evt_error            = 0x4006U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0273_CONF_060,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_MCU_0_R5_3_RESPONSE_THR016_CONF061] =         {
        .host_id            = HOST_ID_MCU_0_R5_3,
        .thread_id            = 16U,
        .threshold            = 1U,
        .evt_threshold            = 0x4007U,
        .evt_error            = 0x4007U,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0272_CONF_061,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM2DMSC_NOTIFY_THR020_CONF062] =         {
        .host_id            = HOST_ID_DM2DMSC,
        .thread_id            = 20U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0271_CONF_062,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DM2DMSC_RESPONSE_THR021_CONF063] =         {
        .host_id            = HOST_ID_DM2DMSC,
        .thread_id            = 21U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0270_CONF_063,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC2DM_NOTIFY_THR025_CONF064] =         {
        .host_id            = HOST_ID_DMSC2DM,
        .thread_id            = 25U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0269_CONF_064,
    },
    [J721E_MCU_NAVSS0_SEC_PROXY0_RX_DMSC2DM_RESPONSE_THR026_CONF065] =         {
        .host_id            = HOST_ID_DMSC2DM,
        .thread_id            = 26U,
        .threshold            = 1U,
        .evt_threshold            = SOC_SAFE_EVENT,
        .evt_error            = SOC_SAFE_EVENT,
        .secure_proxy_instance_id    = J721E_SPROXY_IDX_MCU_NAVSS0_SEC_PROXY0,
        .ring_config_instance_id    = J721E_MCU_NAVSS0_RINGACC0_RING_0268_CONF_065,
    },
};
