/**
 * Note: This file was auto-generated by TI PinMux on 6/10/2020.
 *
 * \file   J7200_pinmux.h
 *
 * \brief  This file contains pad configure register offsets and bit-field 
 *         value macros for different configurations,
 *
 *           BIT[21]		TXDISABLE		disable the pin's output driver
 *           BIT[18]		RXACTIVE		enable the pin's input buffer (typically kept enabled)
 *           BIT[17]		PULLTYPESEL		set the iternal resistor pull direction high or low (if enabled)
 *           BIT[16]		PULLUDEN		internal resistor disable (0 = enabled / 1 = disabled)
 *           BIT[3:0]		MUXMODE			select the desired function on the given pin
 *
 *  \copyright Copyright (CU) 2020 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

#ifndef _J7200_PIN_MUX_H_
#define _J7200_PIN_MUX_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "ti/board/src/j7200_evm/include/pinmux.h"
#include "ti/csl/csl_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
#define PIN_MODE(mode)	                (mode)
#define PINMUX_END                      (-1)

/** \brief Active mode configurations */
/** \brief Resistor enable */
#define PIN_PULL_DISABLE                (0x1U << 16U)
/** \brief Pull direction */
#define	PIN_PULL_DIRECTION              (0x1U << 17U)
/** \brief Receiver enable */
#define	PIN_INPUT_ENABLE                (0x1U << 18U)
/** \brief Driver disable */
#define	PIN_OUTPUT_DISABLE              (0x1U << 21U)
/** \brief Wakeup enable */
#define	PIN_WAKEUP_ENABLE               (0x1U << 29U)

/** \brief Pad config register offset in control module */

enum pinMainOffsets
{
	PIN_TMS		 = 0x11C,
	PIN_RMII1_CRS_DV		 = 0xC,
	PIN_MCAN1_RX		 = 0x2C,
	PIN_MCAN9_TX		 = 0x68,
	PIN_MCAN9_RX		 = 0x6C,
	PIN_GPMC0_CLK		 = 0xAC,
	PIN_SPI0_D1		 = 0xD0,
	PIN_SPI0_CLK		 = 0xC8,
	PIN_SPI0_D0		 = 0xCC,
	PIN_I2C0_SCL		 = 0xD4,
	PIN_I2C0_SDA		 = 0xD8,
	PIN_ECAP0_IN_APWM_OUT		 = 0xDC,
	PIN_EXT_REFCLK1		 = 0xE0,
	PIN_MCAN0_RX		 = 0x24,
	PIN_MCAN0_TX		 = 0x20,
	PIN_MCAN3_RX		 = 0x3C,
	PIN_MCAN3_TX		 = 0x38,
	PIN_MCAN4_RX		 = 0x44,
	PIN_MCAN4_TX		 = 0x40,
	PIN_MCAN5_RX		 = 0x4C,
	PIN_MCAN5_TX		 = 0x48,
	PIN_MCAN6_RX		 = 0x54,
	PIN_MCAN6_TX		 = 0x50,
	PIN_MCAN7_RX		 = 0x5C,
	PIN_MCAN7_TX		 = 0x58,
	PIN_MCAN10_RX		 = 0x74,
	PIN_MCAN10_TX		 = 0x70,
	PIN_MCAN8_RX		 = 0x64,
	PIN_MCAN8_TX		 = 0x60,
	PIN_UART8_TXD		 = 0xA8,
	PIN_UART8_RXD		 = 0xA4,
	PIN_MMC1_CMD		 = 0x104,
	PIN_MMC1_CLK		 = 0x100,
	PIN_MMC1_DAT0		 = 0xF8,
	PIN_MMC1_DAT1		 = 0xF4,
	PIN_MMC1_DAT2		 = 0xF0,
	PIN_MMC1_DAT3		 = 0xEC,
	PIN_TIMER_IO0		 = 0xE4,
	PIN_MCAN11_RX		 = 0x7C,
	PIN_MCAN12_TX		 = 0x80,
	PIN_MCAN12_RX		 = 0x84,
	PIN_MCAN13_TX		 = 0x88,
	PIN_MCAN11_TX		 = 0x78,
	PIN_MCAN13_RX		 = 0x8C,
	PIN_MCAN15_TX		 = 0x90,
	PIN_MCAN15_RX		 = 0x94,
	PIN_UART2_RXD		 = 0x98,
	PIN_UART2_TXD		 = 0x9C,
	PIN_MCAN1_TX		 = 0x28,
	PIN_GPIO0_41		 = 0xA0,
	PIN_EXTINTN		 = 0x0,
	PIN_RESETSTATZ		 = 0x108,
	PIN_SOC_SAFETY_ERRORN		 = 0x110,
	PIN_RMII1_RXD1		 = 0x8,
	PIN_RMII1_RXD0		 = 0x4,
	PIN_RMII1_TXD0		 = 0x14,
	PIN_RMII1_RX_ER		 = 0x10,
	PIN_RMII1_TXD1		 = 0x1C,
	PIN_RMII1_TX_EN		 = 0x18,
	PIN_MCAN2_TX		 = 0x30,
	PIN_MCAN2_RX		 = 0x34,
	PIN_MCAN16_RX		 = 0x168,
	PIN_MCAN16_TX		 = 0x164,
	PIN_UART0_RXD		 = 0xB0,
	PIN_UART0_TXD		 = 0xB4,
	PIN_SPI0_CS0		 = 0xC0,
	PIN_SPI0_CS1		 = 0xC4,
	PIN_UART1_RXD		 = 0xB8,
	PIN_UART1_TXD		 = 0xBC,
	PIN_USB0_DRVVBUS		 = 0x120,
};

enum pinWkupOffsets
{
	PIN_TDI		 = 0x188,
	PIN_TDO		 = 0x18C,
	PIN_EMU0		 = 0x12C,
	PIN_EMU1		 = 0x130,
	PIN_TCK		 = 0x124,
	PIN_TRSTN		 = 0x128,
	PIN_MCU_ADC0_AIN0		 = 0x134,
	PIN_MCU_ADC0_AIN1		 = 0x138,
	PIN_MCU_ADC0_AIN2		 = 0x13C,
	PIN_MCU_ADC0_AIN3		 = 0x140,
	PIN_MCU_ADC0_AIN4		 = 0x144,
	PIN_MCU_ADC0_AIN5		 = 0x148,
	PIN_MCU_ADC0_AIN6		 = 0x14C,
	PIN_MCU_ADC0_AIN7		 = 0x150,
	PIN_MCU_OSPI0_CLK		 = 0x0,
	PIN_MCU_OSPI0_CSN0		 = 0x2C,
	PIN_MCU_OSPI0_D0		 = 0xC,
	PIN_MCU_OSPI0_D1		 = 0x10,
	PIN_MCU_OSPI0_D2		 = 0x14,
	PIN_MCU_OSPI0_D3		 = 0x18,
	PIN_MCU_OSPI0_D4		 = 0x1C,
	PIN_MCU_OSPI0_D5		 = 0x20,
	PIN_MCU_OSPI0_D6		 = 0x24,
	PIN_MCU_OSPI0_D7		 = 0x28,
	PIN_MCU_OSPI0_DQS		 = 0x8,
	PIN_MCU_I2C0_SCL		 = 0x108,
	PIN_MCU_I2C0_SDA		 = 0x10C,
	PIN_WKUP_GPIO0_8		 = 0xE0,
	PIN_WKUP_GPIO0_9		 = 0xE4,
	PIN_WKUP_GPIO0_11		 = 0xEC,
	PIN_MCU_MCAN0_RX		 = 0xBC,
	PIN_MCU_MCAN0_TX		 = 0xB8,
	PIN_WKUP_GPIO0_5		 = 0xD4,
	PIN_WKUP_GPIO0_4		 = 0xD0,
	PIN_MCU_MDIO0_MDC		 = 0x9C,
	PIN_MCU_MDIO0_MDIO		 = 0x98,
	PIN_MCU_RGMII1_RD0		 = 0x94,
	PIN_MCU_RGMII1_RD1		 = 0x90,
	PIN_MCU_RGMII1_RD2		 = 0x8C,
	PIN_MCU_RGMII1_RD3		 = 0x88,
	PIN_MCU_RGMII1_RXC		 = 0x84,
	PIN_MCU_RGMII1_RX_CTL		 = 0x6C,
	PIN_MCU_RGMII1_TD0		 = 0x7C,
	PIN_MCU_RGMII1_TD1		 = 0x78,
	PIN_MCU_RGMII1_TD2		 = 0x74,
	PIN_MCU_RGMII1_TD3		 = 0x70,
	PIN_MCU_RGMII1_TXC		 = 0x80,
	PIN_MCU_RGMII1_TX_CTL		 = 0x68,
	PIN_WKUP_GPIO0_13		 = 0xF4,
	PIN_WKUP_GPIO0_12		 = 0xF0,
	PIN_WKUP_GPIO0_14		 = 0xF8,
	PIN_WKUP_GPIO0_15		 = 0xFC,
	PIN_WKUP_GPIO0_0		 = 0xC0,
	PIN_WKUP_GPIO0_1		 = 0xC4,
	PIN_WKUP_GPIO0_2		 = 0xC8,
	PIN_WKUP_GPIO0_3		 = 0xCC,
	PIN_WKUP_GPIO0_6		 = 0xD8,
	PIN_WKUP_GPIO0_7		 = 0xDC,
	PIN_MCU_SPI0_CLK		 = 0xA0,
	PIN_MCU_SPI0_D0		 = 0xA4,
	PIN_MCU_SPI0_D1		 = 0xA8,
	PIN_MCU_SPI0_CS0		 = 0xAC,
	PIN_WKUP_GPIO0_77		 = 0x120,
	PIN_WKUP_GPIO0_78		 = 0x17C,
	PIN_WKUP_GPIO0_80		 = 0x180,
	PIN_WKUP_GPIO0_84		 = 0x190,
	PIN_WKUP_I2C0_SCL		 = 0x100,
	PIN_WKUP_I2C0_SDA		 = 0x104,
	PIN_WKUP_GPIO0_81		 = 0x184,
	PIN_MCU_RESETSTATZ		 = 0x11C,
	PIN_MCU_RESETZ		 = 0x118,
	PIN_MCU_SAFETY_ERRORN		 = 0x114,
	PIN_PMIC_POWER_EN1		 = 0x110,
	PIN_PMIC_WAKE0		 = 0x124,
	PIN_PORZ		 = 0x178,
	PIN_RESET_REQZ		 = 0x174,
	PIN_WKUP_UART0_RXD		 = 0xB0,
	PIN_WKUP_UART0_TXD		 = 0xB4,
};

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/** \brief Pinmux configuration data for the board. Auto-generated from 
           Pinmux tool. */
extern pinmuxBoardCfg_t gJ7200_MainPinmuxData[];
extern pinmuxBoardCfg_t gJ7200_WkupPinmuxData[];

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _J7200_PIN_MUX_H_ */
