/*============================*/
/*      DDR MEMORY MAP        */
/*============================*/

#define DDR0_RESERVED_START     0x80000000
#define DDR0_RESERVED_SIZE      0x20000000 /* 512MB */

#define DDR0_ALLOCATED_START    0xA0000000 /* DDR0_RESERVED_START + DDR0_RESERVED_SIZE */

#define SHARED_DDR_SPACE_START  0xAA000000
#define SHARED_DDR_SPACE_SIZE   0x01C00000  /*  28MB */

/*------------------------------------------------*/
/* Size of various Memory Locations for each core */ 
/*------------------------------------------------*/
#define IPC_DATA_SIZE   0x00100000 /*  1MB */
#define EXT_DATA_SIZE   0x00100000 /*  1MB */
#define MEM_TEXT_SIZE   0x00100000 /*  1MB */
#define MEM_DATA_SIZE   0x00100000 /*  1MB */
#define DDR_SPACE_SIZE  0x00C00000 /* 12MB */

#define CORE_TOTAL_SIZE 0x01000000 /* 16MB (IPC_DATA_SIZE + R5F_MEM_TEXT_SIZE + R5F_MEM_DATA_SIZE + DDR_SPACE_SIZE) */

/*-----------------------------*/
/* Start address for each core */ 
/*-----------------------------*/

#define MCU1_0_ALLOCATED_START   (DDR0_ALLOCATED_START)
#define MCU1_1_ALLOCATED_START   (MCU1_0_ALLOCATED_START + CORE_TOTAL_SIZE)
#define MCU2_0_ALLOCATED_START   (MCU1_1_ALLOCATED_START + CORE_TOTAL_SIZE)
#define MCU2_1_ALLOCATED_START   (MCU2_0_ALLOCATED_START + CORE_TOTAL_SIZE)
#define MCU3_0_ALLOCATED_START   (MCU2_1_ALLOCATED_START + CORE_TOTAL_SIZE)
#define MCU3_1_ALLOCATED_START   (MCU3_0_ALLOCATED_START + CORE_TOTAL_SIZE)
#define C66x_1_ALLOCATED_START   (MCU3_1_ALLOCATED_START + CORE_TOTAL_SIZE)
#define C66x_2_ALLOCATED_START   (C66x_1_ALLOCATED_START + CORE_TOTAL_SIZE)
#define C7x_1_ALLOCATED_START    (C66x_2_ALLOCATED_START + CORE_TOTAL_SIZE)

/*--------------------------- MCU R5FSS0 CORE0 --------------------------*/
#define MCU1_0_IPC_DATA_BASE     (MCU1_0_ALLOCATED_START)
#define MCU1_0_EXT_DATA_BASE     (MCU1_0_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define MCU1_0_MEM_TEXT_BASE     (MCU1_0_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define MCU1_0_MEM_DATA_BASE     (MCU1_0_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define MCU1_0_DDR_SPACE_BASE    (MCU1_0_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- MCU R5FSS0 CORE1 --------------------------*/
#define MCU1_1_IPC_DATA_BASE     (MCU1_1_ALLOCATED_START)
#define MCU1_1_EXT_DATA_BASE     (MCU1_1_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define MCU1_1_MEM_TEXT_BASE     (MCU1_1_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define MCU1_1_MEM_DATA_BASE     (MCU1_1_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define MCU1_1_DDR_SPACE_BASE    (MCU1_1_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- MAIN R5FSS0 CORE0 -------------------------*/
#define MCU2_0_IPC_DATA_BASE     (MCU2_0_ALLOCATED_START)
#define MCU2_0_EXT_DATA_BASE     (MCU2_0_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define MCU2_0_MEM_TEXT_BASE     (MCU2_0_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define MCU2_0_MEM_DATA_BASE     (MCU2_0_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define MCU2_0_DDR_SPACE_BASE    (MCU2_0_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- MAIN R5FSS0 CORE1 -------------------------*/
#define MCU2_1_IPC_DATA_BASE     (MCU2_1_ALLOCATED_START)
#define MCU2_1_EXT_DATA_BASE     (MCU2_1_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define MCU2_1_MEM_TEXT_BASE     (MCU2_1_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define MCU2_1_MEM_DATA_BASE     (MCU2_1_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define MCU2_1_DDR_SPACE_BASE    (MCU2_1_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- MAIN R5FSS1 CORE0 -------------------------*/
#define MCU3_0_IPC_DATA_BASE     (MCU3_0_ALLOCATED_START)
#define MCU3_0_EXT_DATA_BASE     (MCU3_0_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define MCU3_0_MEM_TEXT_BASE     (MCU3_0_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define MCU3_0_MEM_DATA_BASE     (MCU3_0_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define MCU3_0_DDR_SPACE_BASE    (MCU3_0_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- MAIN R5FSS1 CORE1 -------------------------*/
#define MCU3_1_IPC_DATA_BASE     (MCU3_1_ALLOCATED_START)
#define MCU3_1_EXT_DATA_BASE     (MCU3_1_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define MCU3_1_MEM_TEXT_BASE     (MCU3_1_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define MCU3_1_MEM_DATA_BASE     (MCU3_1_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define MCU3_1_DDR_SPACE_BASE    (MCU3_1_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- C66x DSP CORE1 ----------------------------*/
#define C66x_1_IPC_DATA_BASE     (C66x_1_ALLOCATED_START)
#define C66x_1_EXT_DATA_BASE     (C66x_1_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define C66x_1_MEM_TEXT_BASE     (C66x_1_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define C66x_1_MEM_DATA_BASE     (C66x_1_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define C66x_1_DDR_SPACE_BASE    (C66x_1_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- C66x DSP CORE2 ----------------------------*/
#define C66x_2_IPC_DATA_BASE     (C66x_2_ALLOCATED_START)
#define C66x_2_EXT_DATA_BASE     (C66x_2_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define C66x_2_MEM_TEXT_BASE     (C66x_2_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define C66x_2_MEM_DATA_BASE     (C66x_2_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define C66x_2_DDR_SPACE_BASE    (C66x_2_MEM_DATA_BASE     + MEM_DATA_SIZE)
/*--------------------------- C7x ---------------------------------------*/
#define C7x_1_IPC_DATA_BASE      (C7x_1_ALLOCATED_START)
#define C7x_1_EXT_DATA_BASE      (C7x_1_IPC_DATA_BASE     + IPC_DATA_SIZE)
#define C7x_1_MEM_TEXT_BASE      (C7x_1_EXT_DATA_BASE     + EXT_DATA_SIZE)
#define C7x_1_MEM_DATA_BASE      (C7x_1_MEM_TEXT_BASE     + MEM_TEXT_SIZE)
#define C7x_1_DDR_SPACE_BASE     (C7x_1_MEM_DATA_BASE     + MEM_DATA_SIZE)


MEMORY
{
    DDR0_RESERVED       (RWIX)  : ORIGIN = DDR0_RESERVED_START      LENGTH = DDR0_RESERVED_SIZE 
    /*---------------------------------- MCU R5FSS0 CORE0 ------------------------------*/
    MCU1_0_IPC_DATA     (RWIX)	: ORIGIN = MCU1_0_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU1_0_EXT_DATA     (RWIX)	: ORIGIN = MCU1_0_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU1_0_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU1_0_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU1_0_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU1_0_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU1_0_DDR_SPACE    (RWIX)	: ORIGIN = MCU1_0_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MCU R5FSS0 CORE1 ------------------------------*/
    MCU1_1_IPC_DATA     (RWIX)	: ORIGIN = MCU1_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU1_1_EXT_DATA     (RWIX)	: ORIGIN = MCU1_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU1_1_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU1_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU1_1_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU1_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU1_1_DDR_SPACE    (RWIX)	: ORIGIN = MCU1_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 ------------------------------*/
    MCU2_0_IPC_DATA     (RWIX)	: ORIGIN = MCU2_0_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU2_0_EXT_DATA     (RWIX)	: ORIGIN = MCU2_0_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU2_0_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU2_0_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU2_0_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU2_0_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU2_0_DDR_SPACE    (RWIX)	: ORIGIN = MCU2_0_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 -----------------------------*/
    MCU2_1_IPC_DATA     (RWIX)	: ORIGIN = MCU2_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU2_1_EXT_DATA     (RWIX)	: ORIGIN = MCU2_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU2_1_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU2_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU2_1_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU2_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU2_1_DDR_SPACE    (RWIX)	: ORIGIN = MCU2_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 ------------------------------*/
    MCU3_0_IPC_DATA     (RWIX)	: ORIGIN = MCU3_0_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU3_0_EXT_DATA     (RWIX)	: ORIGIN = MCU3_0_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU3_0_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU3_0_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU3_0_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU3_0_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU3_0_DDR_SPACE    (RWIX)	: ORIGIN = MCU3_0_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- MAIN R5FSS0 CORE0 -----------------------------*/
    MCU3_1_IPC_DATA     (RWIX)	: ORIGIN = MCU3_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    MCU3_1_EXT_DATA     (RWIX)	: ORIGIN = MCU3_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    MCU3_1_R5F_MEM_TEXT (RWIX)	: ORIGIN = MCU3_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    MCU3_1_R5F_MEM_DATA (RWIX)	: ORIGIN = MCU3_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    MCU3_1_DDR_SPACE    (RWIX)	: ORIGIN = MCU3_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- C66x DSP CORE1 ---------------------------------*/
    C66X1_IPC_D         (RWIX)	: ORIGIN = C66x_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    C66X1_EXT_D         (RWIX)	: ORIGIN = C66x_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    C66X1_TEXT          (RWIX)	: ORIGIN = C66x_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    C66X1_DATA          (RWIX)	: ORIGIN = C66x_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    C66X1_DDR_SPACE     (RWIX)	: ORIGIN = C66x_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- C66x DSP CORE2 ---------------------------------*/
    C66X2_IPC_D         (RWIX)	: ORIGIN = C66x_2_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    C66X2_EXT_D         (RWIX)	: ORIGIN = C66x_2_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    C66X2_TEXT          (RWIX)	: ORIGIN = C66x_2_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    C66X2_DATA          (RWIX)	: ORIGIN = C66x_2_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    C66X2_DDR_SPACE     (RWIX)	: ORIGIN = C66x_2_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- C7x-------- -----------------------------------*/
    C7X_IPC_D           (RWIX)	: ORIGIN = C7x_1_IPC_DATA_BASE     LENGTH = IPC_DATA_SIZE
    C7X_EXT_D           (RWIX)	: ORIGIN = C7x_1_EXT_DATA_BASE     LENGTH = EXT_DATA_SIZE
    C7X_TEXT            (RWIX)	: ORIGIN = C7x_1_MEM_TEXT_BASE     LENGTH = MEM_TEXT_SIZE
    C7X_DATA            (RWIX)	: ORIGIN = C7x_1_MEM_DATA_BASE     LENGTH = MEM_DATA_SIZE
    C7X_DDR_SPACE       (RWIX)	: ORIGIN = C7x_1_DDR_SPACE_BASE    LENGTH = DDR_SPACE_SIZE
    /*---------------------------------- Shared Region ----------------------------------------*/
    SHARED_DDR_SPACE    (RWIX)	: ORIGIN = SHARED_DDR_SPACE_START  LENGTH = SHARED_DDR_SPACE_SIZE  
} 
