/******************************************************************************
 * Copyright (c) 2021 Texas Instruments Incorporated - http://www.ti.com
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

 /** \file board_clock.c
  *
  *  \brief AWR294X_EVM Board library clock config file.
  *
  *  PRCM manages clocks, resets, and power domain control of subsystems and
  *  modules inside the device.The Master subsystem TOPRCM module controls all
  *  the Subsystem Resets and Clocks.SubSystem RCM modules control their
  *  respective subsystem modules.
  *
  */

#include "board_clock.h"
#include "board_internal.h"
#include "board_utils.h"

static void Board_moduleClockProgramMode1 (void)
{
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_CR5_DIV_VAL, 0x000);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_CR5_CLK_SRC_SEL, 0x222);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_SYS_CLK_DIV_VAL, 0x111);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_HSI_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_HSI_DIV_VAL_OFFSET, 0x000);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_HSI_CLK_GATE_OFFSET , 0x0);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_TRCCLKOUT_DIV_VAL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_TRCCLKOUT_CLK_SRC_SEL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_CSIRX_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANA_CLK_DIV_VAL_OFFSET, 0x444);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANA_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANB_CLK_DIV_VAL_OFFSET, 0x444);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANB_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RTIA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RTIB_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RTIC_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_WDT_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_QSPI_CLK_DIV_VAL_OFFSET, 0x444);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_QSPI_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SPIA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SPIB_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_I2C_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SCIA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SCIB_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPTS_CLK_DIV_VAL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPTS_CLK_SRC_SEL_OFFSET, 0x333);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_MSS_MII100_CLK_DIV_VAL_OFFSET, 0x999);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_MSS_MII10_CLK_DIV_VAL_OFFSET, 0x636363);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_MSS_RGMII_CLK_DIV_VAL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPSW_CLK_DIV_VAL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPSW_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_RTIA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_WDT_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_RTC_CLK_SRC_SEL_OFFSET, 0x777);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_DMTA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_DMTB_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_DSP_CLK_DIV_VAL, 0x0);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_DSP_CLK_SRC_SEL, 0x222);

    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_RCM_DSS_HWA_CLK_SRC_SEL_OFFSET, 0x000);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_RTIA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_RTIB_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_WDT_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_SCIA_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_RSS_CLK_SRC_SEL_OFFSET, 0x666);
}

static void Board_moduleClockProgramMode2 (void)
{
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_CR5_DIV_VAL, 0x000);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_CR5_CLK_SRC_SEL, 0x222);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_SYS_CLK_DIV_VAL, 0x111);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_HSI_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_HSI_DIV_VAL_OFFSET, 0x000);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_HSI_CLK_GATE_OFFSET, 0x0);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_TRCCLKOUT_DIV_VAL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_TRCCLKOUT_CLK_SRC_SEL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_CSIRX_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANA_CLK_DIV_VAL_OFFSET, 0x444);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANA_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANB_CLK_DIV_VAL_OFFSET, 0x444);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_MCANB_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RTIA_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RTIB_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RTIC_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_WDT_CLK_SRC_SEL_OFFSET, 0x333);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_QSPI_CLK_DIV_VAL_OFFSET, 0x444);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_QSPI_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SPIA_CLK_SRC_SEL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SPIB_CLK_SRC_SEL_OFFSET, 0x111);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_I2C_CLK_SRC_SEL_OFFSET, 0x333);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SCIA_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_SCIB_CLK_SRC_SEL_OFFSET, 0x333);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPTS_CLK_DIV_VAL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPTS_CLK_SRC_SEL_OFFSET, 0x333);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_MSS_MII100_CLK_DIV_VAL_OFFSET, 0x999);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_MSS_MII10_CLK_DIV_VAL_OFFSET, 0x636363);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_MSS_RGMII_CLK_DIV_VAL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPSW_CLK_DIV_VAL_OFFSET, 0x111);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_CPSW_CLK_SRC_SEL_OFFSET, 0x444);

    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_RTIA_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_WDT_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_RTC_CLK_SRC_SEL_OFFSET, 0x777);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_DMTA_CLK_SRC_SEL_OFFSET, 0x333);
    HW_WR_REG32(BOARD_MSS_RCM_U_BASE+BOARD_MSS_RCM_HSM_DMTB_CLK_SRC_SEL_OFFSET, 0x333);

    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_DSP_CLK_DIV_VAL, 0x0);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_DSP_CLK_SRC_SEL, 0x222);

    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_RCM_DSS_HWA_CLK_SRC_SEL_OFFSET, 0x000);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_RTIA_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_RTIB_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_WDT_CLK_SRC_SEL_OFFSET, 0x222);
    HW_WR_REG32(BOARD_DSS_RCM_U_BASE+BOARD_DSS_SCIA_CLK_SRC_SEL_OFFSET, 0x222);

    HW_WR_REG32(BOARD_MSS_TOPRCM_U_BASE+BOARD_MSS_TOPRCM_RSS_CLK_SRC_SEL_OFFSET , 0x666);
}

/**
 * \brief clock Initialization function
 *
 * Enables the clock for all the modules and subsystems by registering the
 * clock source and clokck divider values into their respective clock control
 * registers.
 *
 * \return  BOARD_SOK              - Clock initialization sucessful.
 *          BOARD_INIT_CLOCK_FAIL  - Clock initialization failed.
 *
 */
Board_STATUS Board_moduleClockInit(void)
{
    Board_STATUS status = BOARD_SOK;
    Board_initParams_t boardInitParams;

    Board_getInitParams(&boardInitParams);

    Board_unlockMMR();

    if(boardInitParams.pllMode == BOARD_PLL_MODE2)
    {
        Board_moduleClockProgramMode2();
    }
    else
    {
        Board_moduleClockProgramMode1();
    }

    return status;
}
