/*
*
* Copyright (c) 2021 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/

#ifndef _WKUP_CTRL_MMR_H_
#define _WKUP_CTRL_MMR_H_
#include <ti/drv/lpm/include/io_retention/mx_mmr_mapping.h>
#define WKUP_CTRL_PID                                      (0x00000)
#define WKUP_CTRL_MMR_CFG0                                 (0x00004)
#define WKUP_CTRL_MMR_CFG1                                 (0x00008)
#define WKUP_CTRL_JTAGID                                   (0x00014)
#define WKUP_CTRL_JTAG_USER_ID                             (0x00018)
#define WKUP_CTRL_DIE_ID0                                  (0x00020)
#define WKUP_CTRL_DIE_ID1                                  (0x00024)
#define WKUP_CTRL_DIE_ID2                                  (0x00028)
#define WKUP_CTRL_DIE_ID3                                  (0x0002c)
#define WKUP_CTRL_WKUP_DEVSTAT                             (0x00030)
#define WKUP_CTRL_WKUP_BOOTCFG                             (0x00034)
#define WKUP_CTRL_POST_SEL_STAT                            (0x00038)
#define WKUP_CTRL_POST_OPT                                 (0x0003c)
#define WKUP_CTRL_BOOT_PROGRESS                            (0x00044)
#define WKUP_CTRL_RESET_SRC_STAT                           (0x00050)
#define WKUP_CTRL_DEVICE_FEATURE0                          (0x00060)
#define WKUP_CTRL_DEVICE_FEATURE1                          (0x00064)
#define WKUP_CTRL_DEVICE_FEATURE2                          (0x00068)
#define WKUP_CTRL_DEVICE_FEATURE3                          (0x0006c)
#define WKUP_CTRL_DEVICE_FEATURE5                          (0x00074)
#define WKUP_CTRL_DEVICE_FEATURE6                          (0x00078)
#define WKUP_CTRL_DBG_CBA_ERR_STAT                         (0x00200)
#define WKUP_CTRL_FW_CBA_ERR_STAT                          (0x00204)
#define WKUP_CTRL_NONFW_CBA_ERR_STAT                       (0x00208)
#define WKUP_CTRL_MAIN_CBA_ERR_STAT                        (0x00210)
#define WKUP_CTRL_WKUP_SPARE_FUSE0                         (0x00300)
#define WKUP_CTRL_WKUP_SPARE_FUSE1                         (0x00304)
#define WKUP_CTRL_WKUP_SPARE_FUSE2                         (0x00308)
#define WKUP_CTRL_WKUP_SPARE_FUSE3                         (0x0030c)
#define WKUP_CTRL_LOCK0_KICK0                              (0x01008)
#define WKUP_CTRL_LOCK1_KICK0                              (0x05008)
#define WKUP_CTRL_LOCK2_KICK0                              (0x09008)
#define WKUP_CTRL_LOCK3_KICK0                              (0x0d008)
#define WKUP_CTRL_LOCK4_KICK0                              (0x11008)
#define WKUP_CTRL_LOCK6_KICK0                              (0x19008)
#define WKUP_CTRL_LOCK7_KICK0                              (0x1d008)
#define WKUP_CTRL_LOCK0_KICK1                              (0x0100c)
#define WKUP_CTRL_LOCK1_KICK1                              (0x0500c)
#define WKUP_CTRL_LOCK2_KICK1                              (0x0900c)
#define WKUP_CTRL_LOCK3_KICK1                              (0x0d00c)
#define WKUP_CTRL_LOCK4_KICK1                              (0x1100c)
#define WKUP_CTRL_LOCK6_KICK1                              (0x1900c)
#define WKUP_CTRL_LOCK7_KICK1                              (0x1d00c)
#define WKUP_CTRL_INTR_RAW_STAT                            (0x01010)
#define WKUP_CTRL_INTR_STAT_CLR                            (0x01014)
#define WKUP_CTRL_INTR_EN_SET                              (0x01018)
#define WKUP_CTRL_INTR_EN_CLR                              (0x0101c)
#define WKUP_CTRL_EOI                                      (0x01020)
#define WKUP_CTRL_FAULT_ADDR                               (0x01024)
#define WKUP_CTRL_FAULT_TYPE                               (0x01028)
#define WKUP_CTRL_FAULT_ATTR                               (0x0102c)
#define WKUP_CTRL_FAULT_CLR                                (0x01030)
#define WKUP_CTRL_P0_CLAIM0                                (0x01100)
#define WKUP_CTRL_P0_CLAIM1                                (0x01104)
#define WKUP_CTRL_P0_CLAIM2                                (0x01108)
#define WKUP_CTRL_P0_CLAIM3                                (0x0110c)
#define WKUP_CTRL_P0_CLAIM4                                (0x01110)
#define WKUP_CTRL_P0_CLAIM5                                (0x01114)
#define WKUP_CTRL_P0_CLAIM6                                (0x01118)
#define WKUP_CTRL_MAIN_PWR_CTRL                            (0x04004)
#define WKUP_CTRL_MCU_PWR_CTRL                             (0x04008)
#define WKUP_CTRL_WKUP_GPIO_CTRL                           (0x04020)
#define WKUP_CTRL_WKUP_I2C0_CTRL                           (0x04030)
#define WKUP_CTRL_DBOUNCE_CFG1                             (0x04084)
#define WKUP_CTRL_DBOUNCE_CFG2                             (0x04088)
#define WKUP_CTRL_DBOUNCE_CFG3                             (0x0408c)
#define WKUP_CTRL_DBOUNCE_CFG4                             (0x04090)
#define WKUP_CTRL_DBOUNCE_CFG5                             (0x04094)
#define WKUP_CTRL_DBOUNCE_CFG6                             (0x04098)
#define WKUP_CTRL_H_IO_DRVSTRNGTH0                         (0x040c0)
#define WKUP_CTRL_H_IO_DRVSTRNGTH1                         (0x040c4)
#define WKUP_CTRL_H_IO_DRVSTRNGTH2                         (0x040c8)
#define WKUP_CTRL_H_IO_DRVSTRNGTH3                         (0x040cc)
#define WKUP_CTRL_V_IO_DRVSTRNGTH0                         (0x040d0)
#define WKUP_CTRL_V_IO_DRVSTRNGTH1                         (0x040d4)
#define WKUP_CTRL_V_IO_DRVSTRNGTH2                         (0x040d8)
#define WKUP_CTRL_V_IO_DRVSTRNGTH3                         (0x040dc)
#define WKUP_CTRL_WKUP_SPARE_CTRL0                         (0x04100)
#define WKUP_CTRL_WKUP_SPARE_CTRL1                         (0x04104)
#define WKUP_CTRL_WKUP_SPARE_CTRL2                         (0x04108)
#define WKUP_CTRL_WKUP_SPARE_CTRL3                         (0x0410c)
#define WKUP_CTRL_WKUP_SPARE_CTRL4                         (0x04110)
#define WKUP_CTRL_WKUP_SPARE_CTRL5                         (0x04114)
#define WKUP_CTRL_WKUP_SPARE_CTRL6                         (0x04118)
#define WKUP_CTRL_WKUP_SPARE_CTRL7                         (0x0411c)
#define WKUP_CTRL_WKUP_SPARE_STAT0                         (0x04140)
#define WKUP_CTRL_WKUP_SPARE_STAT1                         (0x04144)
#define WKUP_CTRL_WKUP_SPARE_STAT2                         (0x04148)
#define WKUP_CTRL_WKUP_SPARE_STAT3                         (0x0414c)
#define WKUP_CTRL_WKUP_SPARE_STAT4                         (0x04150)
#define WKUP_CTRL_WKUP_SPARE_STAT5                         (0x04154)
#define WKUP_CTRL_WKUP_SPARE_STAT6                         (0x04158)
#define WKUP_CTRL_WKUP_SPARE_STAT7                         (0x0415c)
#define WKUP_CTRL_P1_CLAIM0                                (0x05100)
#define WKUP_CTRL_P1_CLAIM1                                (0x05104)
#define WKUP_CTRL_P1_CLAIM2                                (0x05108)
#define WKUP_CTRL_MCU_OBSCLK_CTRL                          (0x08000)
#define WKUP_CTRL_HFOSC1_CTRL                              (0x08014)
#define WKUP_CTRL_HFOSC0_TRIM                              (0x08018)
#define WKUP_CTRL_HFOSC1_TRIM                              (0x0801c)
#define WKUP_CTRL_RC12M_OSC_TRIM                           (0x08024)
#define WKUP_CTRL_MCU_PLL_CLKSEL                           (0x08050)
#define WKUP_CTRL_WKUP_PER_CLKSEL                          (0x08060)
#define WKUP_CTRL_WKUP_USART_CLKSEL                        (0x08064)
#define WKUP_CTRL_WKUP_GPIO_CLKSEL                         (0x08070)
#define WKUP_CTRL_MAIN_PLL0_CLKSEL                         (0x08080)
#define WKUP_CTRL_MAIN_PLL1_CLKSEL                         (0x08084)
#define WKUP_CTRL_MAIN_PLL2_CLKSEL                         (0x08088)
#define WKUP_CTRL_MAIN_PLL3_CLKSEL                         (0x0808c)
#define WKUP_CTRL_MAIN_PLL4_CLKSEL                         (0x08090)
#define WKUP_CTRL_MAIN_PLL7_CLKSEL                         (0x0809c)
#define WKUP_CTRL_MAIN_PLL8_CLKSEL                         (0x080a0)
#define WKUP_CTRL_MAIN_PLL12_CLKSEL                        (0x080b0)
#define WKUP_CTRL_MAIN_PLL13_CLKSEL                        (0x080b4)
#define WKUP_CTRL_MAIN_PLL14_CLKSEL                        (0x080b8)
#define WKUP_CTRL_MAIN_SYSCLK_CTRL                         (0x08100)
#define WKUP_CTRL_MCU_SPI0_CLKSEL                          (0x08110)
#define WKUP_CTRL_MCU_SPI1_CLKSEL                          (0x08114)
#define WKUP_CTRL_P2_CLAIM0                                (0x09100)
#define WKUP_CTRL_P2_CLAIM1                                (0x09104)
#define WKUP_CTRL_P2_CLAIM2                                (0x09108)
#define WKUP_CTRL_DMSC_LBIST_CTRL                          (0x0c000)
#define WKUP_CTRL_DMSC_LBIST_PATCOUNT                      (0x0c004)
#define WKUP_CTRL_DMSC_LBIST_SEED0                         (0x0c008)
#define WKUP_CTRL_DMSC_LBIST_SEED1                         (0x0c00c)
#define WKUP_CTRL_DMSC_LBIST_SPARE0                        (0x0c010)
#define WKUP_CTRL_DMSC_LBIST_SPARE1                        (0x0c014)
#define WKUP_CTRL_DMSC_LBIST_STAT                          (0x0c018)
#define WKUP_CTRL_DMSC_LBIST_MISR                          (0x0c01c)
#define WKUP_CTRL_DMSC_LBIST_SIG                           (0x0c280)
#define WKUP_CTRL_WKUP_POST_STAT                           (0x0c2c0)
#define WKUP_CTRL_WKUP_POST_CFG0                           (0x0c2c4)
#define WKUP_CTRL_WKUP_POST_CFG1                           (0x0c2cc)
#define WKUP_CTRL_WKUP_FUSE_CRC_CTRL                       (0x0c300)
#define WKUP_CTRL_WKUP_CHAIN1_CRC_FUSE                     (0x0c304)
#define WKUP_CTRL_WKUP_CHAIN2_CRC_FUSE                     (0x0c308)
#define WKUP_CTRL_WKUP_FUSE_CRC_STAT                       (0x0c320)
#define WKUP_CTRL_WKUP_CHAIN1_CRC_CALC                     (0x0c324)
#define WKUP_CTRL_WKUP_CHAIN2_CRC_CALC                     (0x0c328)
#define WKUP_CTRL_P3_CLAIM0                                (0x0d100)
#define WKUP_CTRL_P3_CLAIM1                                (0x0d104)
#define WKUP_CTRL_P3_CLAIM2                                (0x0d108)
#define WKUP_CTRL_P3_CLAIM3                                (0x0d10c)
#define WKUP_CTRL_P3_CLAIM4                                (0x0d110)
#define WKUP_CTRL_P3_CLAIM5                                (0x0d114)
#define WKUP_CTRL_P3_CLAIM6                                (0x0d118)
#define WKUP_CTRL_DV_REG0                                  (0x10000)
#define WKUP_CTRL_DV_REG1                                  (0x10004)
#define WKUP_CTRL_DV_REG2                                  (0x10008)
#define WKUP_CTRL_DV_REG3                                  (0x1000c)
#define WKUP_CTRL_DV_REG4                                  (0x10010)
#define WKUP_CTRL_DV_REG5                                  (0x10014)
#define WKUP_CTRL_DV_REG6                                  (0x10018)
#define WKUP_CTRL_DV_REG7                                  (0x1001c)
#define WKUP_CTRL_DV_REG8                                  (0x10020)
#define WKUP_CTRL_DV_REG9                                  (0x10024)
#define WKUP_CTRL_DV_REG10                                 (0x10028)
#define WKUP_CTRL_DV_REG11                                 (0x1002c)
#define WKUP_CTRL_DV_REG12                                 (0x10030)
#define WKUP_CTRL_DV_REG13                                 (0x10034)
#define WKUP_CTRL_DV_REG14                                 (0x10038)
#define WKUP_CTRL_DV_REG15                                 (0x1003c)
#define WKUP_CTRL_DV_REG16                                 (0x10040)
#define WKUP_CTRL_DV_REG17                                 (0x10044)
#define WKUP_CTRL_DV_REG18                                 (0x10048)
#define WKUP_CTRL_DV_REG19                                 (0x1004c)
#define WKUP_CTRL_DV_REG20                                 (0x10050)
#define WKUP_CTRL_DV_REG21                                 (0x10054)
#define WKUP_CTRL_DV_REG22                                 (0x10058)
#define WKUP_CTRL_DV_REG23                                 (0x1005c)
#define WKUP_CTRL_DV_REG24                                 (0x10060)
#define WKUP_CTRL_DV_REG25                                 (0x10064)
#define WKUP_CTRL_DV_REG26                                 (0x10068)
#define WKUP_CTRL_DV_REG27                                 (0x1006c)
#define WKUP_CTRL_DV_REG28                                 (0x10070)
#define WKUP_CTRL_DV_REG29                                 (0x10074)
#define WKUP_CTRL_DV_REG30                                 (0x10078)
#define WKUP_CTRL_DV_REG31                                 (0x1007c)
#define WKUP_CTRL_DV_REG32                                 (0x10080)
#define WKUP_CTRL_DV_REG33                                 (0x10084)
#define WKUP_CTRL_DV_REG34                                 (0x10088)
#define WKUP_CTRL_DV_REG35                                 (0x1008c)
#define WKUP_CTRL_DV_REG36                                 (0x10090)
#define WKUP_CTRL_DV_REG37                                 (0x10094)
#define WKUP_CTRL_DV_REG38                                 (0x10098)
#define WKUP_CTRL_DV_REG39                                 (0x1009c)
#define WKUP_CTRL_DV_REG40                                 (0x100a0)
#define WKUP_CTRL_DV_REG41                                 (0x100a4)
#define WKUP_CTRL_DV_REG42                                 (0x100a8)
#define WKUP_CTRL_DV_REG43                                 (0x100ac)
#define WKUP_CTRL_DV_REG44                                 (0x100b0)
#define WKUP_CTRL_DV_REG45                                 (0x100b4)
#define WKUP_CTRL_DV_REG46                                 (0x100b8)
#define WKUP_CTRL_DV_REG47                                 (0x100bc)
#define WKUP_CTRL_DV_REG48                                 (0x100c0)
#define WKUP_CTRL_DV_REG49                                 (0x100c4)
#define WKUP_CTRL_DV_REG50                                 (0x100c8)
#define WKUP_CTRL_DV_REG51                                 (0x100cc)
#define WKUP_CTRL_DV_REG52                                 (0x100d0)
#define WKUP_CTRL_DV_REG53                                 (0x100d4)
#define WKUP_CTRL_DV_REG54                                 (0x100d8)
#define WKUP_CTRL_DV_REG55                                 (0x100dc)
#define WKUP_CTRL_DV_REG56                                 (0x100e0)
#define WKUP_CTRL_DV_REG57                                 (0x100e4)
#define WKUP_CTRL_DV_REG58                                 (0x100e8)
#define WKUP_CTRL_DV_REG59                                 (0x100ec)
#define WKUP_CTRL_DV_REG60                                 (0x100f0)
#define WKUP_CTRL_DV_REG61                                 (0x100f4)
#define WKUP_CTRL_DV_REG62                                 (0x100f8)
#define WKUP_CTRL_DV_REG63                                 (0x100fc)
#define WKUP_CTRL_DV_REG0_SET                              (0x10200)
#define WKUP_CTRL_DV_REG1_SET                              (0x10204)
#define WKUP_CTRL_DV_REG2_SET                              (0x10208)
#define WKUP_CTRL_DV_REG3_SET                              (0x1020c)
#define WKUP_CTRL_DV_REG4_SET                              (0x10210)
#define WKUP_CTRL_DV_REG5_SET                              (0x10214)
#define WKUP_CTRL_DV_REG6_SET                              (0x10218)
#define WKUP_CTRL_DV_REG7_SET                              (0x1021c)
#define WKUP_CTRL_DV_REG8_SET                              (0x10220)
#define WKUP_CTRL_DV_REG9_SET                              (0x10224)
#define WKUP_CTRL_DV_REG10_SET                             (0x10228)
#define WKUP_CTRL_DV_REG11_SET                             (0x1022c)
#define WKUP_CTRL_DV_REG12_SET                             (0x10230)
#define WKUP_CTRL_DV_REG13_SET                             (0x10234)
#define WKUP_CTRL_DV_REG14_SET                             (0x10238)
#define WKUP_CTRL_DV_REG15_SET                             (0x1023c)
#define WKUP_CTRL_DV_REG16_SET                             (0x10240)
#define WKUP_CTRL_DV_REG17_SET                             (0x10244)
#define WKUP_CTRL_DV_REG18_SET                             (0x10248)
#define WKUP_CTRL_DV_REG19_SET                             (0x1024c)
#define WKUP_CTRL_DV_REG20_SET                             (0x10250)
#define WKUP_CTRL_DV_REG21_SET                             (0x10254)
#define WKUP_CTRL_DV_REG22_SET                             (0x10258)
#define WKUP_CTRL_DV_REG23_SET                             (0x1025c)
#define WKUP_CTRL_DV_REG24_SET                             (0x10260)
#define WKUP_CTRL_DV_REG25_SET                             (0x10264)
#define WKUP_CTRL_DV_REG26_SET                             (0x10268)
#define WKUP_CTRL_DV_REG27_SET                             (0x1026c)
#define WKUP_CTRL_DV_REG28_SET                             (0x10270)
#define WKUP_CTRL_DV_REG29_SET                             (0x10274)
#define WKUP_CTRL_DV_REG30_SET                             (0x10278)
#define WKUP_CTRL_DV_REG31_SET                             (0x1027c)
#define WKUP_CTRL_DV_REG0_CLR                              (0x10300)
#define WKUP_CTRL_DV_REG1_CLR                              (0x10304)
#define WKUP_CTRL_DV_REG2_CLR                              (0x10308)
#define WKUP_CTRL_DV_REG3_CLR                              (0x1030c)
#define WKUP_CTRL_DV_REG4_CLR                              (0x10310)
#define WKUP_CTRL_DV_REG5_CLR                              (0x10314)
#define WKUP_CTRL_DV_REG6_CLR                              (0x10318)
#define WKUP_CTRL_DV_REG7_CLR                              (0x1031c)
#define WKUP_CTRL_DV_REG8_CLR                              (0x10320)
#define WKUP_CTRL_DV_REG9_CLR                              (0x10324)
#define WKUP_CTRL_DV_REG10_CLR                             (0x10328)
#define WKUP_CTRL_DV_REG11_CLR                             (0x1032c)
#define WKUP_CTRL_DV_REG12_CLR                             (0x10330)
#define WKUP_CTRL_DV_REG13_CLR                             (0x10334)
#define WKUP_CTRL_DV_REG14_CLR                             (0x10338)
#define WKUP_CTRL_DV_REG15_CLR                             (0x1033c)
#define WKUP_CTRL_DV_REG16_CLR                             (0x10340)
#define WKUP_CTRL_DV_REG17_CLR                             (0x10344)
#define WKUP_CTRL_DV_REG18_CLR                             (0x10348)
#define WKUP_CTRL_DV_REG19_CLR                             (0x1034c)
#define WKUP_CTRL_DV_REG20_CLR                             (0x10350)
#define WKUP_CTRL_DV_REG21_CLR                             (0x10354)
#define WKUP_CTRL_DV_REG22_CLR                             (0x10358)
#define WKUP_CTRL_DV_REG23_CLR                             (0x1035c)
#define WKUP_CTRL_DV_REG24_CLR                             (0x10360)
#define WKUP_CTRL_DV_REG25_CLR                             (0x10364)
#define WKUP_CTRL_DV_REG26_CLR                             (0x10368)
#define WKUP_CTRL_DV_REG27_CLR                             (0x1036c)
#define WKUP_CTRL_DV_REG28_CLR                             (0x10370)
#define WKUP_CTRL_DV_REG29_CLR                             (0x10374)
#define WKUP_CTRL_DV_REG30_CLR                             (0x10378)
#define WKUP_CTRL_DV_REG31_CLR                             (0x1037c)
#define WKUP_CTRL_LED_CTRL                                 (0x10400)
#define WKUP_CTRL_LED_ENABLE                               (0x10408)
#define WKUP_CTRL_LED_MCU_PLL_STAT_EN                      (0x10420)
#define WKUP_CTRL_LED_MAIN_PLL_STAT_EN                     (0x10424)
#define WKUP_CTRL_LED_PGD_STAT_EN                          (0x10428)
#define WKUP_CTRL_LED_EFC_STAT_EN                          (0x1042c)
#define WKUP_CTRL_LED_STATUS_CTRL                          (0x10430)
#define WKUP_CTRL_SIM_CFG0                                 (0x10480)
#define WKUP_CTRL_SIM_CFG1                                 (0x10484)
#define WKUP_CTRL_SIM_CFG2                                 (0x10488)
#define WKUP_CTRL_SIM_CFG3                                 (0x1048c)
#define WKUP_CTRL_SIM_CFG4                                 (0x10490)
#define WKUP_CTRL_SIM_CFG5                                 (0x10494)
#define WKUP_CTRL_SIM_CFG6                                 (0x10498)
#define WKUP_CTRL_SIM_CFG7                                 (0x1049c)
#define WKUP_CTRL_WKUP_MRGN_MODE0                          (0x10500)
#define WKUP_CTRL_WKUP_MRGN_MODE1                          (0x10504)
#define WKUP_CTRL_WKUP_MRGN_MODE2                          (0x10508)
#define WKUP_CTRL_WKUP_MRGN_MODE3                          (0x1050c)
#define WKUP_CTRL_WKUP_MRGN_MODE4                          (0x10510)
#define WKUP_CTRL_WKUP_MRGN_MODE5                          (0x10514)
#define WKUP_CTRL_WKUP_MRGN_MODE6                          (0x10518)
#define WKUP_CTRL_WKUP_MRGN_MODE7                          (0x1051c)
#define WKUP_CTRL_WKUP_MRGN_MODE8                          (0x10520)
#define WKUP_CTRL_WKUP_MRGN_MODE9                          (0x10524)
#define WKUP_CTRL_P4_CLAIM0                                (0x11100)
#define WKUP_CTRL_P4_CLAIM1                                (0x11104)
#define WKUP_CTRL_P4_CLAIM2                                (0x11108)
#define WKUP_CTRL_P4_CLAIM3                                (0x1110c)
#define WKUP_CTRL_P4_CLAIM4                                (0x11110)
#define WKUP_CTRL_P4_CLAIM5                                (0x11114)
#define WKUP_CTRL_P4_CLAIM6                                (0x11118)
#define WKUP_CTRL_P4_CLAIM7                                (0x1111c)
#define WKUP_CTRL_P4_CLAIM8                                (0x11120)
#define WKUP_CTRL_P4_CLAIM9                                (0x11124)
#define WKUP_CTRL_P4_CLAIM10                               (0x11128)
#define WKUP_CTRL_POR_CTRL                                 (0x18000)
#define WKUP_CTRL_POR_STAT                                 (0x18004)
#define WKUP_CTRL_POK_VDDA_PMIC_IN_CTRL                    (0x18010)
#define WKUP_CTRL_POK_VDDSHV_WKUP_GEN_UV_CTRL              (0x18014)
#define WKUP_CTRL_POK_VDDR_MCU_UV_CTRL                     (0x18018)
#define WKUP_CTRL_POK_VMON_CAP_MCU_GEN_UV_CTRL             (0x1801c)
#define WKUP_CTRL_POK_VDD_MCU_OV_CTRL                      (0x18020)
#define WKUP_CTRL_POK_VDDSHV_WKUP_GEN_OV_CTRL              (0x18024)
#define WKUP_CTRL_POK_VDDR_MCU_OV_CTRL                     (0x18028)
#define WKUP_CTRL_POK_VMON_CAP_MCU_GEN_OV_CTRL             (0x1802c)
#define WKUP_CTRL_MAIN_VDOM_CTRL                           (0x18070)
#define WKUP_CTRL_POR_POKHV_UV_CTRL                        (0x18080)
#define WKUP_CTRL_POR_POKLVB_UV_CTRL                       (0x18084)
#define WKUP_CTRL_POR_POKLVA_OV_CTRL                       (0x18088)
#define WKUP_CTRL_POR_BANDGAP_CTRL                         (0x1808c)
#define WKUP_CTRL_TEMP_DIODE_TRIM                          (0x180a0)
#define WKUP_CTRL_IO_VOLTAGE_STAT                          (0x180b0)
#define WKUP_CTRL_MAIN_POR_TO_CTRL                         (0x18104)
#define WKUP_CTRL_POK_VDD_CORE_UV_CTRL                     (0x18110)
#define WKUP_CTRL_POK_VDD_CPU_UV_CTRL                      (0x18114)
#define WKUP_CTRL_POK_VMON_EXT_UV_CTRL                     (0x18118)
#define WKUP_CTRL_POK_VDDR_CORE_UV_CTRL                    (0x1811c)
#define WKUP_CTRL_POK_VDD_CORE_OV_CTRL                     (0x18120)
#define WKUP_CTRL_POK_VDD_CPU_OV_CTRL                      (0x18124)
#define WKUP_CTRL_POK_VMON_EXT_OV_CTRL                     (0x18128)
#define WKUP_CTRL_POK_VDDR_CORE_OV_CTRL                    (0x1812c)
#define WKUP_CTRL_POK_VMON_EXT_MAIN1P8_UV_CTRL             (0x18130)
#define WKUP_CTRL_POK_VMON_EXT_MAIN1P8_OV_CTRL             (0x18134)
#define WKUP_CTRL_POK_VMON_EXT_MAIN3P3_UV_CTRL             (0x18138)
#define WKUP_CTRL_POK_VMON_EXT_MAIN3P3_OV_CTRL             (0x1813c)
#define WKUP_CTRL_POK_RSV0                                 (0x18150)
#define WKUP_CTRL_POK_RSV1                                 (0x18154)
#define WKUP_CTRL_POK_RSV2                                 (0x18158)
#define WKUP_CTRL_POK_RSV3                                 (0x1815c)
#define WKUP_CTRL_DEEPSLEEP_CTRL                           (0x18160)
#define WKUP_CTRL_POR_RST_CTRL                             (0x18170)
#define WKUP_CTRL_MAIN_WARM_RST_CTRL                       (0x18174)
#define WKUP_CTRL_RST_STAT                                 (0x18178)
#define WKUP_CTRL_MCU_WARM_RST_CTRL                        (0x1817c)
#define WKUP_CTRL_VDD_CPU_GLDTC_CTRL                       (0x18180)
#define WKUP_CTRL_VDD_CORE_GLDTC_CTRL                      (0x18190)
#define WKUP_CTRL_VDDR_CPU_GLDTC_CTRL                      (0x18194)
#define WKUP_CTRL_VDDR_CORE_GLDTC_CTRL                     (0x18198)
#define WKUP_CTRL_VDD_CPU_GLDTC_STAT                       (0x181a0)
#define WKUP_CTRL_VDD_CORE_GLDTC_STAT                      (0x181b0)
#define WKUP_CTRL_VDDR_CPU_GLDTC_STAT                      (0x181b4)
#define WKUP_CTRL_VDDR_CORE_GLDTC_STAT                     (0x181b8)
#define WKUP_CTRL_VDD_MCU_GLDTC_CTRL                       (0x181c0)
#define WKUP_CTRL_VDDR_MCU_GLDTC_CTRL                      (0x181c4)
#define WKUP_CTRL_VDD_MCU_GLDTC_STAT                       (0x181d0)
#define WKUP_CTRL_VDDR_MCU_GLDTC_STAT                      (0x181d4)
#define WKUP_CTRL_PRG_PP_MCU_CTRL                          (0x18200)
#define WKUP_CTRL_PRG_PP_MCU_STAT                          (0x18204)
#define WKUP_CTRL_PRG_PP_POR_CTRL                          (0x18208)
#define WKUP_CTRL_PRG_PP_POR_STAT                          (0x1820c)
#define WKUP_CTRL_PRG_PP_MAIN_CTRL                         (0x18210)
#define WKUP_CTRL_PRG_PP_MAIN_STAT                         (0x18214)
#define WKUP_CTRL_WKUP_CLKGATE_CTRL                        (0x18280)
#define WKUP_CTRL_MCU_CLKGATE_CTRL                         (0x18284)
#define WKUP_CTRL_MAIN_CLKGATE_CTRL0                       (0x18288)
#define WKUP_CTRL_MAIN_CLKGATE_CTRL1                       (0x1828c)
#define WKUP_CTRL_CANUART_WAKE_CTRL                        (0x18300)
#define WKUP_CTRL_CANUART_WAKE_STAT0                       (0x18308)
#define WKUP_CTRL_CANUART_WAKE_STAT1                       (0x1830c)
#define WKUP_CTRL_MCU_GEN_WAKE_CTRL                        (0x18310)
#define WKUP_CTRL_MCU_GEN_WAKE_STAT0                       (0x18318)
#define WKUP_CTRL_MCU_GEN_WAKE_STAT1                       (0x1831c)
#define WKUP_CTRL_P6_CLAIM0                                (0x19100)
#define WKUP_CTRL_P6_CLAIM1                                (0x19104)
#define WKUP_CTRL_P6_CLAIM2                                (0x19108)
#define WKUP_CTRL_P6_CLAIM3                                (0x1910c)
#define WKUP_CTRL_P6_CLAIM4                                (0x19110)
#define WKUP_CTRL_P6_CLAIM5                                (0x19114)
#define WKUP_CTRL_P6_CLAIM6                                (0x19118)
#define WKUP_CTRL_PADCONFIG0                               (0x1c000)
#define WKUP_CTRL_PADCONFIG1                               (0x1c004)
#define WKUP_CTRL_PADCONFIG2                               (0x1c008)
#define WKUP_CTRL_PADCONFIG3                               (0x1c00c)
#define WKUP_CTRL_PADCONFIG4                               (0x1c010)
#define WKUP_CTRL_PADCONFIG5                               (0x1c014)
#define WKUP_CTRL_PADCONFIG6                               (0x1c018)
#define WKUP_CTRL_PADCONFIG7                               (0x1c01c)
#define WKUP_CTRL_PADCONFIG8                               (0x1c020)
#define WKUP_CTRL_PADCONFIG9                               (0x1c024)
#define WKUP_CTRL_PADCONFIG10                              (0x1c028)
#define WKUP_CTRL_PADCONFIG11                              (0x1c02c)
#define WKUP_CTRL_PADCONFIG12                              (0x1c030)
#define WKUP_CTRL_PADCONFIG14                              (0x1c038)
#define WKUP_CTRL_PADCONFIG15                              (0x1c03c)
#define WKUP_CTRL_PADCONFIG26                              (0x1c068)
#define WKUP_CTRL_PADCONFIG27                              (0x1c06c)
#define WKUP_CTRL_PADCONFIG28                              (0x1c070)
#define WKUP_CTRL_PADCONFIG29                              (0x1c074)
#define WKUP_CTRL_PADCONFIG30                              (0x1c078)
#define WKUP_CTRL_PADCONFIG31                              (0x1c07c)
#define WKUP_CTRL_PADCONFIG32                              (0x1c080)
#define WKUP_CTRL_PADCONFIG33                              (0x1c084)
#define WKUP_CTRL_PADCONFIG34                              (0x1c088)
#define WKUP_CTRL_PADCONFIG35                              (0x1c08c)
#define WKUP_CTRL_PADCONFIG36                              (0x1c090)
#define WKUP_CTRL_PADCONFIG37                              (0x1c094)
#define WKUP_CTRL_PADCONFIG38                              (0x1c098)
#define WKUP_CTRL_PADCONFIG39                              (0x1c09c)
#define WKUP_CTRL_PADCONFIG40                              (0x1c0a0)
#define WKUP_CTRL_PADCONFIG41                              (0x1c0a4)
#define WKUP_CTRL_PADCONFIG42                              (0x1c0a8)
#define WKUP_CTRL_PADCONFIG43                              (0x1c0ac)
#define WKUP_CTRL_PADCONFIG44                              (0x1c0b0)
#define WKUP_CTRL_PADCONFIG45                              (0x1c0b4)
#define WKUP_CTRL_PADCONFIG46                              (0x1c0b8)
#define WKUP_CTRL_PADCONFIG47                              (0x1c0bc)
#define WKUP_CTRL_PADCONFIG48                              (0x1c0c0)
#define WKUP_CTRL_PADCONFIG49                              (0x1c0c4)
#define WKUP_CTRL_PADCONFIG50                              (0x1c0c8)
#define WKUP_CTRL_PADCONFIG51                              (0x1c0cc)
#define WKUP_CTRL_PADCONFIG52                              (0x1c0d0)
#define WKUP_CTRL_PADCONFIG53                              (0x1c0d4)
#define WKUP_CTRL_PADCONFIG54                              (0x1c0d8)
#define WKUP_CTRL_PADCONFIG55                              (0x1c0dc)
#define WKUP_CTRL_PADCONFIG56                              (0x1c0e0)
#define WKUP_CTRL_PADCONFIG57                              (0x1c0e4)
#define WKUP_CTRL_PADCONFIG58                              (0x1c0e8)
#define WKUP_CTRL_PADCONFIG59                              (0x1c0ec)
#define WKUP_CTRL_PADCONFIG60                              (0x1c0f0)
#define WKUP_CTRL_PADCONFIG61                              (0x1c0f4)
#define WKUP_CTRL_PADCONFIG62                              (0x1c0f8)
#define WKUP_CTRL_PADCONFIG63                              (0x1c0fc)
#define WKUP_CTRL_PADCONFIG64                              (0x1c100)
#define WKUP_CTRL_PADCONFIG65                              (0x1c104)
#define WKUP_CTRL_PADCONFIG66                              (0x1c108)
#define WKUP_CTRL_PADCONFIG67                              (0x1c10c)
#define WKUP_CTRL_PADCONFIG68                              (0x1c110)
#define WKUP_CTRL_PADCONFIG69                              (0x1c114)
#define WKUP_CTRL_PADCONFIG70                              (0x1c118)
#define WKUP_CTRL_PADCONFIG71                              (0x1c11c)
#define WKUP_CTRL_PADCONFIG72                              (0x1c120)
#define WKUP_CTRL_PADCONFIG73                              (0x1c124)
#define WKUP_CTRL_PADCONFIG74                              (0x1c128)
#define WKUP_CTRL_PADCONFIG75                              (0x1c12c)
#define WKUP_CTRL_PADCONFIG76                              (0x1c130)
#define WKUP_CTRL_PADCONFIG77                              (0x1c134)
#define WKUP_CTRL_PADCONFIG78                              (0x1c138)
#define WKUP_CTRL_PADCONFIG79                              (0x1c13c)
#define WKUP_CTRL_PADCONFIG80                              (0x1c140)
#define WKUP_CTRL_PADCONFIG81                              (0x1c144)
#define WKUP_CTRL_PADCONFIG82                              (0x1c148)
#define WKUP_CTRL_PADCONFIG83                              (0x1c14c)
#define WKUP_CTRL_PADCONFIG84                              (0x1c150)
#define WKUP_CTRL_PADCONFIG93                              (0x1c174)
#define WKUP_CTRL_PADCONFIG94                              (0x1c178)
#define WKUP_CTRL_PADCONFIG95                              (0x1c17c)
#define WKUP_CTRL_PADCONFIG96                              (0x1c180)
#define WKUP_CTRL_PADCONFIG97                              (0x1c184)
#define WKUP_CTRL_PADCONFIG98                              (0x1c188)
#define WKUP_CTRL_PADCONFIG99                              (0x1c18c)
#define WKUP_CTRL_PADCONFIG100                             (0x1c190)
#define WKUP_CTRL_P7_CLAIM0                                (0x1d100)
#define WKUP_CTRL_P7_CLAIM1                                (0x1d104)
#define WKUP_CTRL_P7_CLAIM2                                (0x1d108)
#define WKUP_CTRL_P7_CLAIM3                                (0x1d10c)
#endif

